# -*- coding: utf-8 -*-
"""
Created on Wed Apr  8 17:36:15 2020

@author: Aneta
"""
echa_microplastics=[
 'polyethylene',
 ' polyethylene',
 'polyethylene [+/- ci 77891',
 'oxidized polyethylene',
 'polyethylene wax',
 'polymethyl methacrylate',
 'methyl methacrylate crosspolymer',
 'ptfe',
 'polyurethane crosspolymer-2',
 'nylon-6ti/dimethicone copolymer',
 'nylon-611/dimethicone copolymer',
 'nylon-6',
 'nylon-12',
 'styrene/acrylates/ammonium methacrylate copolymer',
 'styrene/acrylates/ ammonium methacrylate copolymer',
 'styrene/acrylates copolymer',
 'styrene/acrylates',
 'styrene / acrylates copolymer',
 'styrene/acrylate copolymer',
 'styrene / acrylates / ammonium methacrylate copolymer',
 'styrene/arcylates copolymer',
 'polyethylene terephthalate',
 'polyethylene terephithalate',
 'polybutylene terephthalate',
 'terephthalate',
 'acrylates/vinyl neodecanoate crosspolymer',
 'sodium acrylates copolymer',
 'acrylates/vinyl isodecanoate crosspolymer',
 'acrylates copolymer',
 'sodium acrylate/sodium acryloyldimethyl taurate copolymer',
 'acrylates/c10-30/alkyl acrylate crosspolymer',
 'polyacrylate crosspolymer-6',
 'acrylates/c10-30 alkyl acrylate crosspolymer',
 'hydroxyethyl acrylate/sodium acryloyldimethyl taurate copolymer',
 'pvm/ma copolymer',
 'glyceryl acrylate/acrylic acid copolymer',
 'polyacrylate-13',
 'methyl methacrylate/glycol dimethacrylate crosspolymer',
 'sodium polyacrylate',
 'glyceryl polymethacrylate',
 'acrylonitrile/methyl methacrylate/vinylidene chloride copolymer',
 'ammonium polyacryloyldimethyl taurate',
 'acrylamide/sodium acryloyldimethyltaurate copolymer',
 'acrylonitrile/methyl methacrylate/vinylidene chloride',
 'copolymer',
 'ammonium acryloyldimethyl-taurate/steareth-25 methacrylate crosspolymer',
 'ammonium acryloyldimethyl - taurate/steareth-25 methacrylate crosspolymer',
 'acrylamide / sodium acryloyldimethyltaurate copolymer',
 'ammonium polyacryldimethyltauramide/ammonium polyacryloyldimethyl taurate',
 'dimethicone/polyglycerin-3 crosspolymer',
 'sodim acrylates copolymer',
 'ammonium polyacryldimethyltauramide / ammonium polyacryloyldimethyl taurate',
 'acrylonitrile / methylmethacrylate / vinylidene chloride copolymer',
 'polyacrylate-21',
 'acrylates/dimethylaminoethyl methacrylate copolymer',
 'glyceryl polymethacrylate',
 'sodium acryloyldimethyltaurate/vp crosspolymer',
 'acrylates/beheneth-25 methacrylate copolymer',
 'acrylates crosspolymer-4',
 'potassium acrylates copolymer',
 'acrylic acid/acrylamidomethyl propane sulfonic acid copolymer',
 'acrylamide/ammonium acrylate copolymer',
 'octylacrylamide/acrylates/butylaminoethyl methacrylate copolymer',
 'sodium polymetnacrylate',
 'rosin acrylate',
 'sodium polymethacrylate',
 'acrylates/octylacrylamide copolymer',
 'acrylates/dimethicone copolymer',
 'lauryl methacrylate/glycol dimethacrylate crosspolymer',
 'ethylene/acrylic acid copolymer',
 'sodium polemethacrylate',
 'ethylene/methacrylate copolymer',
 'acrylic acid/isobutyl acrylate/isobornyl acrylate copolymer',
 'acrylonitrile/methyl methacrylte/vinylidene chloride copolymer',
 'acrylonitrile/methyl methacrylate/vinylidene chloride copolymer aluminum hydroxide',
 'acrylates/c12-22 alkyl methacrylate copolymer',
 'acrylamidopropyltrimonium chloride/acrylamide copolymer',
 'ammonium polyacryldimethyl tauramide/ammonium polyacryloyldimethyl taurate',
 'sodium polynaphthalenesulfonate',
 'carbober',
 'ammonium acryloydimethyltaurate/vp copolymer',
 'ammonium polyacryldimethyltauramide/ammonium',
 'sodium acrylates/c10-30 alkyl acrylate',
 'polyacrylate crosspolymer-9',
 'acrylates/t-butylacrylamide copolymer',
 'sodium acrylate/acryloyldimethyltaurate/dimethylacrylamide crosspolymer',
 'dimethylacrylamide/ethyltrimonium chloride methacrylate copolymer',
 'vinyl caprolactam/vp/dimethylaminoethyl methacrylate copolymer',
 'vp/dmapa acrylates copolymer',
 'acrylates/hydroxyesters acrylates copolymer',
 'acrylates/steareth-20 methacrylate crosspolymer',
 'acrylamidopropyltrimonium chloride/acrylates copolymer',
 'ethylhexyl acrylate/methyl methacrylate copolymer',
 'acrylates/steareth-20 itaconate copolymer',
 'acrylamidopropyltrimoniumchloride/acrylates copolymer',
 'amp-acrylates/allyl methacrylate copolymer',
 'vinyl capropactam/vp/dimethylaminoethyl methacrylate copolymer',
 'acrylates/stearyl acrylate/ethylamine oxide methacrylate copolymer',
 'acrylates/steareth-20 methacrylate copolymer',
 'pvp/va copolymer',
 'vp/methacrylamide/vinyl imidazole copolymer',
 'vp/dimethylaminoethylmethacrylate copolymer',
 'vp/vinyl caprolactam/dmapa acrylates copolymer',
 'butyl ester of pvm/ma copolymer',
 'calcium/zinc pvm/ma copolymer (33%)',
 'calcium/zinc pvm/ma copolymer',
 'calcium/zinc pvm/ma copolymer (35%)',
 'calcium/sodium pvm/ma co-polymer',
 'calcium/sodium pvm/ma copolymer',
 'c30-45 alxyldimethylsilyl polypropylsilsesquioxane',
 'polymethylsilsesquioxane',
 'polymethylsilses-quioxane',
 'polypropylsilsesquioxane',
 'c30-45 alkyldimethylsilyl polypropylsilsesquioxane',
 'vinyl dimethicone/methicone silsesquioxane crosspolymer',
 'vinyl dimethicnone/methicone silsesquioxane crosspolymer',
 'diphenyl dimethicone/vinyl diphenyl dimethicone/silsesquioxane crosspolymer',
 'vinyl dimethicone / methicone silsesquioxane crosspolymer',
 'amodimethicone/morpholinomethyl silsesquioxane copolymer',
 'amodimethicone/morpholinomethyl silsequioxane copolymer',
 'dimethiconol/silsesquioxane copolymer',
 'c30-45 alkyldimethylsilyl popypropylsilsesquioxane'
     ]
other_synthetic_polymer= [
 'polyester-4',
 'polyester-5',
 'polyester-23',
 'polyurethane-35',
 'polyurethane-39',
 'polyurethane-48',
 'polyurethane-11',
 'polyurethane-33',
 'hydrogenated polycylopentadiene',
 'hydrogenated polydecene',
 'ethylene/propylene copolymer',
 'hydrohenated polyisobutene',
 'hydrogenated styrene/isoprene copolymer',
 'polyamide-2',
 'polybutene',
 'polyacrylamide',
 'hydrogenated polyisobutene',
 'pvp',
 'carbomer',
 'polyvinyl butyral',
 'polyvinyl alcohol',
 'polyisobutene',
 'ammonium acryloyldimethyltaurate/vp copolymer',
 'sodium polyacryate',
 'sodium carbomer',
 'sodium polystyrene sulfonate',
 'polysilicone-11',
 'dimethicone crosspolymer',
 'ethylene/va copolymer',
 'dimethicone/vinyl dimethicone crosspolymer',
 'ethylene/va copolymer propylparaben',
 'vp/va copolymer',
 'strawberry: polybutene',
 'ananas: polybutene',
 'orange: polybutene',
 'blueberry: polybutene',
 'peppermint: polybutene',
 'apple: polybutene',
 'cherry: polybutene',
 'magnesium aluminum silicate polyacrylamide',
 'hydrogenated polycyclopentadiene',
 'hydrogenated poly(c6-14 olefin)',
 'hydrogenated polyisobutane',
 'polyvinyl laurate',
 'polybutene ozokerite',
 'polyvinyl acetate',
 'aqua (and) polyvinyl alcohol (and) polyvinyl acetate',
 'hdi/trimethylol hexyllactone crosspolymer',
 'adipic acid/neopentyl glycol/trimellitic anhydride copolymer',
 'c30-45 alkyl cetearyl dimethicone crosspolymer',
 'vp/hexadecene copolymer',
 'ppg-17/ipdi/dmpa copolymer',
 'vp/eicosene copolymer',
 'crosspolymer',
 'ethylene/propylene/styrene copolymer',
 'polyimide-1',
 'butylene/ethylene/styrene copolymer',
 'vp/hexadecane copolymer',
 'plolybutene',
 'acetylates copolymer',
 'adipic acid/furmatic acid/tricyclodecane dimenthanol copolymer',
 'phthalic anhydride/trimellitic anhydride/glycols copolymer',
 'phthalic anhydride / trimellitic anhydride / glycols copolymer',
 'adipic acia/neopentyl glycol/trimellitic anhydride copolymer',
 'adipic acid/fumaric acid/tricyclodecane dimethanol copolymer',
 'phthalic anhydride/glycerin/glycidyl decanoate copolymer',
 'tosylamide/epoxy resin',
 'hydrogenated acetophenone/oxymethylene copolymer',
 'ethylenediamine/stearyl dimer dilinoleate copolymer',
 'divinyldimethicone/dimethicone copolymer',
 'dilinoleic acid/butanediol copolymer',
 'allyl stearate va copolymer',
 'vp eicosene copolymer',
 'allyl stearate/va copolymer',
 'silica dimethicone/polyglycerin-3 crosspolymer',
 'polyurea crosspolymer-2',
 'polyurea crosspolymer-3',
 'steareth-100/peg-136/hdi copolymer',
 'polyacryloyldimethyl taurate',
 'maltodextrin/vp copolymer',
 'polyquaternium crosspolymer-3',
 'polyvinylcaprolactam',
 'styrene/vp copolymer'
]
polyether=[
 'poloxamer 407',
 'poloxamer 184',
 'poloxamer 338',
 'peg-45/dodecyl glycol copolymer',
 'ppg-1-peg-9 lauryl glycol ether',
 'poloxamer 231',
 'peg-9/ppg-7/mdi copolymer',
 'dimethicone/peg-10/15 crosspolymer',
 'peg-12 dimethicone',
 'peg-400',
 'peg-10 dimethicone',
 'peg-45m',
 'cetyl peg/ppg-10/1 dimethicone',
 'bis-peg/ppg-14/14 dimethicone',
 'peg/ppg-18/18 dimethicone',
 'bis-peg-18 methyl ether dimethyl silane',
 'cetyl peg-ppg-10/1 dimethicone',
 'peg/ppg-17/18 dimethicone',
 'peg-9 polydimethylsiloxyethyl dimethicone',
 'lauryl peg-9 polydimethylsiloxyethyl dimethicone',
 'bis-peg/ppg-16/16 peg/ppg-16/16 dimethicone',
 'dimethiconol peg-8',
 'peg-14m',
 'peg-90m',
 'peg-23m',
 'dimethicone peg/ppg-20/23 benzoate',
 'peg-7m',
 'peg/ppg-18/18',
 'peg/ppg-8/3 laurate',
 'lauryl peg-9 polydimethylsiloxeythyl dimethicone',
 'peg 90m',
 'peg-75 stearate',
 'peg/ppg-120/10 trimethylpropane trioleate',
 'lauryl peg/ppg-18/18 methicone',
 'cetyl peg/ppg-10/1 dimeticone',
 'peg-90 m',
 'peg-2m',
 'peg-12 allyl ether',
 'peg-12',
 'peg/ppg -18/18 dimethicone',
 'peg-180m',
 'peg/ppg-20/15 dimethicone',
 'peg-150',
 'peg-25 paba',
 'hydrated silica peg-32',
 'peg-8/smdi copolymer',
 'steareth-100 / peg-136 / hdi copolymer',
 'steareth-100/peg-136/hdi copolymer',
 'bis-diisopropanolamino-pg-propyl dimethicone/bis-isobutyl peg-14 copolymer',
 'bis-isobutyl peg/ppg-20/35/amodimethicone copolymer',
 'peg-100 stearate',
 'peg-8',
 'peg-20 glyceryl triisostearate',
 'peg-40 hydrogenated castor oil',
 'sodium peg-7 olive oil carboxylate',
 'olive oil peg-7 esters',
 'peg-6 caprylic/capric glycerides',
 'peg-20 glyceryl stearate',
 'peg-40 sorbitan peroleate',
 'peg-40 stearate',
 'peg-8 stearate',
 'peg-9',
 'peg-7 glyceryl cocoate',
 'peg-8 beeswax',
 'peg-32',
 'peg-150 pentaerythrityl tetrastearate',
 'peg-60 hydrogenated castor oil',
 'peg-200 hydrogenated glyceryl palmate',
 'peg-55 propylene glycol oleate',
 'peg-20 stearate',
 'peg-20 methyl glucose sesquistearate',
 'peg-30 dipolyhydroxystearate',
 'peg-120 methyl glucose dioleate',
 'peg-8 laurate',
 'peg-5 ethylhexanoate',
 'peg-3 distearate',
 'peg-14 m',
 'peg-90 glyceryl isostearate',
 'peg-80 hydrogenated glyceryl palmate',
 'peg 120 methyl glucose dioleate',
 'peg-6-caprylic/capric glycerides',
 'peg-6 hydrogenated castor oil',
 'peg-20',
 'disodium peg-5 laurylcitrate sulfosuccinate',
 'peg-30 glyceryl stearate',
 'peg-200 glyceryl stearate',
 'peg-5 rapeseed sterol',
 'peg-8 distearate',
 'peg-4',
 'peg 40 hydrogenated castor oil',
 'peg-150 distearate',
 'peg-4 rapeseedamide',
 'peg-5 cocomonium methosulfate',
 'peg-7 hydrogenated castor oil',
 'peg-5-ethylhexanoate',
 'peg-4 dialurate',
 'peg-4 laurate',
 'peg-4 dilaurate',
 'peg-150 pentaerythrityl tetrasearate',
 'peg-7 glyceryl cocate',
 'peg-5 glyceryl stearate',
 'peg-5 glyceril stearate',
 'peg-2 hydrogenated castor oil',
 'peg-20 castor oil',
 'peg-20 glyceryl laurate',
 'peg-40 sorbitan perisostearate',
 'peg-7 propylheptyl ether',
 'peg-8 bees wax',
 'peg-4 distearyl ether',
 'peg-2 oleamine',
 'peg-40 castor oil',
 'peg-60 almond glycerides',
 'peg-4 castor oil',
 'peg-40 hydrogenated hastor oil',
 'peg 150 distearate',
 'peg-7 propylheptyl ethyl',
 'peg-7 propyheptyl ether',
 'peg-15 hydroxystearate',
 'peg-35 caastor oil',
 'peg-3 tallow aminopropylamine',
 'peg-6']
mineral=[
 'aqua (purified water)',
 'kaolin (natural clay)',
 'ci 77891 (titanium dioxide)',
 'maris sal (sea salt)',
 'ci 77499 (iron oxides)',
 'bentonite (natural clay)',
 'illite (mediterranean clay)',
 'pumice (black lava)',
 'potassium hydroxide',
 'aqua',
 'sodium chloride',
 'sodium hydroxide',
 'silica',
 'kaolin',
 'disodium phosphate',
 'sodium bisulfite',
 'tin oxid',
 'magnesium sulfate',
 'sodium sulfite',
 'phosphoric acid',
 'sodium potassium aluminum silicate',
 'titanium dioxide',
 'bentonite',
 'maris sal',
 'mica',
 'potassium phosphate',
 'zinc oxide',
 'sodium chloride*',
 'magnesium aluminum silicate',
 '*dead sea salt',
 'sea salt',
 'iron oxides (ci 77491)',
 'denní krém: aqua / water',
 'noční krém: aqua / water',
 'aqua/water',
 'ci 77891/titanium dioxide',
 'aqua / water',
 'dipotassium phosphate',
 'perlite',
 'ci 77499/iron oxides',
 'stearalkonium hectorite',
 'denní krém: aqua/water',
 'noční krém: aqua/water',
 'titanium dioxide [nano]/titanium dioxide',
 'alumina',
 'tin oxide',
 'pottasium hydroxide',
 'cl 77499 / iron oxides',
 'moroccan lava clay',
 'zinc sulfate',
 'ci 77499 / iron oxides',
 'ci 77510 / ferric ferrocyanide',
 'ci 77163/bismuth oxychloride',
 'silica [nano] / silica',
 'sodium nitrate',
 'silica [nano]/silica',
 'sodium sulfate',
 'sodium phosphate',
 'hydratační noční maska: aqua',
 'denní krém: aqua',
 'noční krém: aqua',
 'talc',
 'water',
 'sea mud',
 'aqua/[water]',
 'aqua (water)',
 'magnesium nitrate',
 'magnesium chloride',
 'calcium carbonate',
 'bicarbonate',
 'sodium monofluorophosphate (1450 ppm f")',
 'sodium bicarbonate',
 'tetra sodium pyrophosphate',
 'obsahuje: sodium monofluorophosphate (1450 ppm f")',
 'zinc chloride',
 'sodium fluoride',
 'obsahuje fluorid sodný (220 ppm f)',
 'aluminum chlorohydrate',
 'agua',
 'aqua/water/eau',
 'aluminum hydroxide',
 'sapphire powder',
 'magnesium silicate',
 'calcium aluminum borosilicate',
 'tin oxide]',
 'barium sulfate',
 'make-up: aqua',
 'magnesium carbonate',
 'boron nitride',
 '1. talc',
 '2. mica',
 '3. mica',
 '4. mica',
 'calcium sodium borosilicate',
 '2. talc',
 '3. talc',
 '4. talc',
 '4. calcium sodium borosilicate',
 'sodium silicoaluminate',
 'lithium magnesium sodium silicate',
 '3 shades: mica',
 'matte eyeshadow: mica',
 'silicon dioxide',
 'shimmer eyeshadow: mica',
 '[+/- may contain: mica',
 'step 1: aqua/water',
 'calcium titanium borosilicate',
 'silica silylate [nano]/silica silylate',
 'dicalcium phosphate',
 'ci77510/ferric ferrocyanide',
 'silica silylate [nano] / silica silylate',
 'hydrated silica',
 'diammonium phosphate',
 'titanium dioxide (nano)',
 'magensium stearate',
 '[+/- may contain mica',
 'titanium dioxide [nano] / titanium dioxide',
 'mica]',
 'aqua (demineralized water)',
 'aqua(water)',
 '+/-: mica',
 'aqua ((water) eau)',
 '[may contain: mica',
 'iron oxides (cl 77491',
 'cl 77499)',
 'ultramarines (cl 77007)]',
 'aluminium hydroxide',
 '[may contain/peut contenir/+/-: mica',
 '[may contain: titanium dioxide (cl 77891)',
 'kapalina (1) : aqua',
 'barvicí gel (2) : aqua',
 'silver nitrate',
 'ammonium hydroxide',
 'water (aqua',
 'eau)',
 'water (aqua/eau)',
 'water/eau (aqua)',
 'hectorite',
 'diamond powder',
 'aluminum calcium sodium silicate',
 'g804779: talc',
 'step 2: aqua/water',
 '[+/- may concaine mica',
 '[+/- may containe moca',
 'calcium',
 'sodium bororsilicate',
 '[+/- may containe mica',
 '[+/-may contain mica',
 'aluminum hydrocide',
 'sulfuric acid',
 'phosphate',
 'silica [nano]/silica caprylic/capric glycerides',
 'lithium magnesium sodium silicate [nano] / lithium magnesium',
 'sodium silicate',
 'ci77499/iron oxides',
 'ci77891/titanium dioxide]',
 'calcium aluminium borosilicate',
 'magnesium silica',
 'sodium choride',
 'aqua / water / eau',
 'aluminum zirconium',
 'silver chloride',
 'potassium alum',
 'aqua (water',
 'aluminum sesquichlorohydrate',
 'calcium chloride',
 'lime & coffee: sodium bicarbonate',
 'champagne rose: sodium bicarbonate',
 'levander & orange: sodium bicarbonate',
 'mango & blackberry: sodium bicarbonate',
 'aluminum stearate',
 'maris sal (sea salt',
 'sel marin)',
 'magnesium aluminometasilicate',
 'aluminum',
 'chlorohydrate',
 'sodium metabisulfite',
 'sodium hyroxide',
 'aluminum zirconium pentachlorohydrate',
 'water/eau',
 'aluminium chlorohydrate',
 'modrá: sodium bicarbonate',
 'růžová: sodium bicarbonate',
 'oranžová: sodium bicarbonate',
 'zelená: sodium bicarbonate',
 'aqua (water) (agua)',
 'aqua\xa0(water) (agua)',
 'sodium thiosulfate',
 'potassium iodate',
 'aluminum  chlorohydrate',
 'maris sal (magnesium chloride (and) potassium chloride (and) sodium chloride (and) calcium chloride (and) potassium bromide)',
 'calcium hydroxide',
 'magnesium trisilicate',
 'hydrogen peroxide',
 'potassium persulfate',
 'ammonium persulfate',
 'sodium metasilicate',
 'sodium persulfate',
 'magnesium carbonate hydroxide',
 'barvicí krém: aqua/water',
 'oxidační činidlo: aqua/water',
 'tetrasodium pyrophosphate',
 'závěrečná péče: aqua/water',
 'barvící krém: aqua/water',
 'lichtening powder: potassium persulfate',
 'ammonium chloride',
 'magnesium hydroxide',
 'magnesium peroxide',
 'developer creme: aqua / water',
 'argilla / magnesium aluminum silicate',
 'argilla/magnesium aluminum silicate',
 'ochranné sérum: aqua / water',
 'barvící krém: aqua / water',
 'oxidační činidlo: aqua / water',
 'závěrečná péče: aqua / water',
 'ochranné sérum: aqua/water',
 'barvicí krém: aqua / water',
 'phospohoric acid',
 'barvicí činidlo: aqua / water',
 'barvicí činidlo: aqua/water',
 'sodium stannate',
 'barvicí krém: aqua',
 'vyvíjecí mléko: aqua',
 'disodium pyrophosphate',
 'bohatá pečující maska: aqua',
 'zesvětlující prášek: potassium persulfate',
 'sodium hexametaphosphate',
 'potassium sulfate',
 'ammonium sulfate',
 'zesvětlující krém: aqua',
 'vyvíječ: aqua',
 'platinová pečující maska: aqua',
 'posilovač zesvětlení ultra plus/blond: potassium persulfate',
 'quartz',
 'barvicí krém: aqua (water',
 'vyvíječ: aqua (water',
 'pečující maska: aqua (water',
 'zesvětlující krém: aqua (water',
 'posilovač pro blond vlasy: potassium persulfate',
 'pečující balzám: aqua (water',
 'potassium hydroxyde',
 'péče po barvení: aqua',
 'balzám: aqua',
 'pečující balzám: aqua',
 'vyvíjecí emulze: aqua',
 'vyvíjecí mléko: aqua (water',
 'bohatá pečující maska: aqua (water',
 'arvicí krém: aqua',
 'pečující maska: aqua',
 'disodium pyrophoshpate',
 'disodium pyrophoshate',
 'moagnesium chloride',
 'sodium',
 'zesvětlující aktivátor: potassium persulfate',
 'barvicí gel: aqua (water',
 'pečující balzám na vlasy: aqua (water',
 'barvicí gel: aqua',
 'pečující balzám na vlasy: aqua',
 'kondicionér: aqua',
 'balzám: aqua (water',
 'aktivátor zesvětlení ultra plus: potassium persulfate',
 'salonplex balzám: aqua',
 'bohatá olejová péče: aqua',
 'šampon: aqua (water)',
 'kondicionér: aqua (water)',
 'studená vlna: aqua',
 'tekutý fixater: aqua',
 'obsahuje: fluorid sodný',
 'obsahuje: fluorid sodný 0',
 'tetrapotassium pyrophosphate',
 'calcium fluoride',
 'obsahuje fluor (500ppmf)',
 'aluminium fluoride',
 'hydroxyapatite',
 'pentasodium triphosphate',
 'obsahuje fluorid sodný (450 ppm f)',
 'obsahuje: fluorid sodný (220 ppmf)',
 'potassium nitrate',
 'pottasium nitrate',
 'stannous fluoride',
 'hydrochloric acid',
 'obsah fluoridů: 1400 ppm',
 'obsahuje fluorid sodný (1450 ppm f)',
 'obsahuje fluorid sodný (250 ppm f)',
 'obsahuje fluorid sodný (1050 ppm f)',
 'obsahuje fluorid sodný (1450 ppm)',
 'sodiumhexametaphosphate',
 'stannous chloride',
 'trisodium phosphate',
 'obsahuje fluorid sodný 0',
 '31% w/w (1400 ppm f)',
 '31 % w/w (1400 ppm f)',
 '315% w/w (1450 ppm f)',
 '3152% w/w (1426ppm)',
 'obsahuje fluorid cínatý 0.454% (1100 ppm f)',
 'fluorid sodný (1450 ppm)',
 'dusičnan draselný 5% w/w',
 'obsahuje fluorid sodný (1450 ppm) a dusičnan draselný 5% w/w',
 'obsahuje fluorid cínatý 0',
 '454% w/w',
 'fluorid sodný 0',
 '0721% w/w (1450 ppm f)',
 '0721% w/w (1450 ppmf)',
 'calcium sodium phosphosilicate (novamin)',
 'calcium sodium',
 'phosphosilicate (novamin)',
 'tetrapottasium pyrophosphate',
 'sodium monofluorophosphate',
 'calcium glycerophosphate',
 'obsahuje fluorofosforečnan sodný (1450 ppm f)',
 'monosodium phosphate',
 'obsahuje: fluoriod sodný (1450 ppm f)',
 'obsahuje sodium fluoride (1450 ppm f)',
 'calcium peroxide',
 'potassium thiocyanate']
readily_degradable= ['glycerin (plant origin)',
 'alcohol denat.',
 'gelatin crosspolymer',
 'phenoxyethanol',
 'rayon',
 'xanthan gum (natural thickener)',
 'ethylhexylglycerin',
 'tocopheryl (vitamin e) acetate',
 'cereus grandiflorus (cactus) flower extract',
 'benzyl salicylate',
 'citric acid (plant origin)',
 'hamamelis virginiana (with hazel) leaf extract',
 'punica granatum (pomegranate) fruit extract',
 'propanediol (plant origin)',
 'phenethyl alcohol',
 'undecyl alcohol',
 'potassium sorbate',
 'porphyra umbilicalis (laver seaweed) extract',
 'tocopherol (vitamin e)',
 'hippophae rhamnoides (sea buckthorn) fruit extract',
 'sodium benzoate',
 'juglans regia (walnut) shell powder',
 'sodium citrate (plant origin)',
 'charcoal powder',
 'cetyl alcohol (plant origin)',
 'glyceryl stearate (plant origin)',
 'propylene glycol',
 'sucrose stearate (sugar origin)',
 'sucrose tristearate (sugar origin)',
 'caprylyl glycol',
 'panax ginseng root extract',
 'amyl cinnamal',
 'ficus carica (fig) fruit extract',
 'butylene glycol',
 'cetyl ethylhexanoate (plant origin)',
 'cetearyl alcohol (plant origin)',
 'betaine (plant origin)',
 'butyrospermum parkii (shea) butter',
 'ginkgo biloba leaf extract',
 'prunus amygdalus dulcis (sweet almond) oil',
 'olus oil',
 'argania spinosa (argan) kemel oil',
 'citrus limon (citrus medica limonum) (lemon) fruit extract',
 'glycine soja (soybean) seed extract',
 'lycium chinense (goji berry) fruit extract',
 'thuja orientalis (thuja) seed extract',
 'swertia japonica extract',
 'laminaria japonica (seaweed) extract',
 'mentha piperita (peppermint) leaf extract',
 'polysorbate 60',
 'sorbitan sesquioleate (plant origin)',
 'stearic acid (plant origin)',
 'illicium verum (anise) fruit extract',
 '2-hexanediol',
 'salicylic acid',
 'hexyl cinnamal',
 'linalool',
 'glyceryl stearate',
 'ethylhexyl salicylate',
 'glycerin',
 'cetearyl alcohol',
 'ethylhexyl stearate',
 'c12-15 alkyl benzoate',
 'ceteareth-20',
 'caprylic/capric triglyceride',
 'butyrospermum parkii butter',
 'cetyl palmitate',
 'alaria esculenta extract',
 'ceteareth-12',
 'tocopheryl acetate',
 'panthenol',
 'soluble collagen',
 'glycogen',
 'hydrolyzed elastin',
 'glucose',
 'fructose',
 'maltose',
 'urea',
 'trehalose',
 'allantoin',
 'sodium hyaluronate',
 'tocopherol',
 'sodium lactate',
 'glyceryl laurate',
 'pentylene glycol',
 'citric acid',
 'sorbic acid',
 'ascorbic acid',
 'ascorbyl palmitate',
 'sodium succinate',
 'hydrogenated microcrystalline wax',
 'stearic acid',
 'hydrogenated vegetable glycerides',
 'glyceryl stearate citrate',
 'prunus amygdalus dulcis oil',
 'bis-diglyceryl polyacyladipate-2',
 'sodium stearoyl glutamate',
 'triethanolamine',
 'hydrocycitronellal',
 'limonene',
 'coumarin',
 'geraniol',
 'isoeugenol',
 'alpha-glucan oligosaccharide',
 'bisabolol',
 'diethylhexyl syringylidenemalonate',
 'paeonia officinalis flower extract',
 'polysorbate 20',
 'sorbitan isostearate',
 'dicaprylyl ether',
 'arachidyl alcohol',
 'arachidyl glucoside',
 'behenyl alcohol',
 'camellia sinensis leaf extract',
 'coco-glucoside',
 'tapioca starch',
 'ricinus communis seed oil',
 'helianthus annuus seed oil',
 'cera alba',
 'helianthus annuus seed cera',
 'hydrogenated vegetable oil',
 'ethylhexyl methoxycinnamate',
 'polyglyceryl-3',
 'diisostearate',
 'theobroma cacao seed butter',
 'simmondsia chinesis seed oil',
 'stevia rebaudiana extract',
 'sorbitol',
 'argania spinosa kernel oil',
 'lactic acid',
 'polyglyceryl -3 methylglucose distearate',
 'cetyl palmatine',
 'bis-diglyceryl polyacyladipate-2',
 'macadamia ternifolia seed oil',
 'lecithin',
 'propanediol',
 'glycosaminoglycans',
 'ascorbyl palmatine',
 'tocopheryl',
 'acetate',
 'hydrogenated castor oil',
 'copernicia cerifera cera',
 'soidum benzoate',
 'pistacia vera seed oil',
 'olea europaea fruit oil',
 'prunus armeniaca kernel oil',
 'capryloyl glycine',
 'moringa oleifera seed extract',
 'lysolecithin',
 'sodium acetate',
 'xanthan gum',
 'glycereth-7 caprylate/caprate',
 'cetrimonium bromide',
 'copper gluconate',
 'magnesium aspartate',
 'zinc gluconate',
 'hydroxypropyl cyclodextrin',
 'palmitoyl tripeptide-38',
 'citrid acid',
 'citronellol',
 'passiflora edulis fruit extract',
 'citrus limon fruit extract',
 'cichorium intybus root oligosaccharides',
 'caesalpinia spinosa gum',
 'ficus carica fruit extract',
 'gluconolactone',
 'glycine soja oil',
 'glycine soja sterols',
 'hydrogenated palm glycerides citrate',
 'stearyl stearate',
 'isopropyl palmitate',
 'ethylhexyl palmitate',
 'glucomannan',
 'hydrolyzed yeast extract',
 'polyglucuronic acid',
 'trihydroxystearin',
 'pottasium sorbate',
 'polyglyceryl-3 diisostearate',
 'aloe barbadensis leaf juice powder',
 'sodium laureth sulfate',
 'benzyl alcohol',
 'isopropyl myristate',
 'caledula officinalis flower extract',
 'hydroxycitronellal',
 'lanolin',
 'palmitic acid',
 'pentaerythrityl distearate',
 'alcohol',
 'diisopropyl adipate',
 'ubiquinone',
 'butylphenyl methylpropional',
 'almond oil',
 'glycereth-8 esters',
 'allantoin panthenol',
 'betaine',
 'gossypium herbaceum seed extract',
 'polyhydroxystearic acid',
 'mel extract',
 'calcium gluconate',
 'sodium bezoate',
 'o-cymen-5-ol',
 'benzyl benzoate',
 'ethyl butyrate',
 'raspberry ketone',
 'vanillin',
 'ethy 2-methylbutyrate',
 'broskev: ethylhexyl palmitate',
 ' tridecyl trimellitate',
 ' caprylic/capric triglyceride',
 ' cera alba',
 ' phenoxyethanol',
 ' tocopheryl acetate',
 ' ethylhexylglycerin',
 ' 2-pentyl acetate',
 ' amyl butyrate',
 ' ethyl acetate',
 ' ethyl butyrate',
 ' citrus aurantium bergamia fruit oil',
 'vodní meloun: ethylhexyl palmitate',
 ' citral',
 ' eugenol',
 'melaleuca alternifolia leaf oil',
 'menthol',
 'niacinamide',
 'hydrogenated coconut oil',
 'cetyl alcohol',
 'glyceryl stearate se',
 'cyclotetrapeptide-24 aminocyclohexane carboxylate',
 'sorbitan caprylate',
 'inositol',
 'cannabis sativa seed oil',
 'cannabis sativa leaf extract',
 'copper tripeptide-1',
 'tridecyl trimellitate',
 '2-pentyl acetate',
 'amyl butyrate',
 'ethyl acetate',
 'citrus aurantium bergamia fruit oil',
 'citral',
 'eugenol',
 'cypryloyl glycine',
 'cannabis sativa leaf extrakt',
 'sodium cocoyl glutamate',
 'xanthan',
 'caprylol glycine',
 'cocamine oxide',
 'ethylglycerin',
 'resvaratrol',
 'bee honey',
 'butoryspermum parkii butter',
 'prunus amygdalus sativa kernel oil',
 'eucalyptus globulus leaf oil',
 'methyl lactate',
 'sodium citrate',
 'decyl oleate',
 'dicocoyl pantaerythrityl distearyl citrate',
 'sorbitate sesquioleate',
 'mustela (mink) oil',
 'aluminum stearates',
 'sodium cetearyl sulfate',
 'd-limonene',
 'dicocoyl pentaerythrityl distearyl citrate',
 'sorbitan sesquioleate',
 'magnesium stearate',
 'benzyl cinnamate',
 'cetearyl glucosid',
 'nannochloropsis oculata extract',
 'spent grain wax',
 'butyrospermum parkii butter extract',
 'cocamidopropyl betaine',
 'chondrus crispus (carrageenan) extract',
 'cucumis sativus juice',
 'glyceryl oleate',
 'mannitol',
 'xylitol',
 'fructooligosaccharides',
 'laureth-7',
 'pentapeptide-18',
 'acetyl hexapeptide-8',
 'tetrasodium glutamate diacetate',
 'squalane',
 'acmella oleracea extract',
 'chamomilla recutita flower extract',
 'polysorbate 80',
 'sorbitan oleate',
 'cetearyl ethylhexanoate',
 'myristyl myristate',
 'potassium cetyl phosphate',
 'hydrogenated olive oil',
 'hydrogenated palm glycerides',
 'hydrolyted collagen',
 'aesculus hippocastanum (horse chestnut) extract',
 'olea europaea oil unsaponifiables',
 'tetrasodium glutamate',
 'diacetate',
 'octyldodecanol',
 'hydrolyzed collagen',
 'tricedeth-6',
 'cetearyl glucoside',
 'alagria esculenta extract',
 'sucrose laurate',
 'caviar extract',
 'calendula officinalis flower extract',
 'peg-40 stearate',
 'prunus cerasus fruit extract',
 'isopropyl alcohol',
 'cellulose',
 'sucrose cocoate',
 'sucrose palmitate',
 'hydrogenated vegetable glicerides',
 'vitis vinifera seed oil',
 'simmondsia chinensis seed oil',
 'ispropyl myristate',
 'ethylhexyl olivate',
 'avena sativa kernel extract',
 'formic acid',
 'hexanediol',
 'dicaprylyl carbonate',
 'carthamus tinctorius seed oil',
 'hexyldecanol',
 'cocoglycerides',
 'quassia amara extract',
 'pyrus malus seed extract',
 'plankton extract',
 'dimethylsilanol hyaluronate',
 'bis-ethylhexyl hydroxydimethoxy benzylmalonate',
 'echium plantagineum seed oil',
 'tapioca strach',
 'caprylyl/capryl glucoside',
 'cetearyl isononanoate',
 'hydrolyzed yeast protein',
 'micrococcus lysate',
 'caffeine',
 'hydrolyzed soy protein',
 'hibiscus abelmoschus seed extract',
 'palmitoyl tripeptide-1',
 'palmitoyl tetrapeptide-7',
 'glycyrrhiza glabra',
 'glyceryl linoleate',
 'trideceth-9',
 'c12-15 alcohols',
 't-butyl alcohol',
 'beeswax',
 'hippophae rhamnoides berries extract and rosmarinus officinalis leaf extract',
 'euphorbia cerifera cera',
 'butyl stearate',
 'glycine soja oil (and) calendula officinalis flower extract',
 'camelia sinensis leaf extract',
 'peg-7 glyceryl cocoate',
 'mentha piperita oil',
 'ethylhexyl dimethyl paba',
 'glutamine',
 'decyl glucoside',
 'cistus incanus flower/leaf/stem extract',
 'gynostemma pentaphyllum leaf/stem extract',
 'ethyhexylglycerin',
 'phenylpropanol',
 'beta-sitosterol',
 'squalene',
 'propyl galate',
 'hydrogenated vegetable glycerides citrate',
 'porphyridium cruentum extract',
 'methylpropanediol',
 'cetearyl',
 'disodium adenosine triphosphate',
 'carica papaya fruit extract',
 'algin',
 'polysorbate-60',
 'hyaluronic acid',
 'caprylic/capric triglyceride (and) citrus limon (lemon) peel extract (and) citrus aurantium dulcis (orange) fruit extract (and) citrus aurantiifolia (lime) peel extract (and) salvia officinalis (sage) leaf extract (and) pyrus malus (apple) fruit extract (and) vanilla planifolia fruit extract (and) cucumis sativus (cucumber) fruit extract',
 'tocopherol acetate',
 'retinyl palmitate',
 'caprylic/capric tryglyceride',
 'mannan',
 'benzoic acid',
 'dehydroacetic acid',
 'ceteareth- 20',
 'ceteareth- 12',
 'algae extract',
 'cetearyl alcholol',
 'glycine',
 'kigelia africana fruit extract',
 'quillaja saponaria bark extract',
 'hippophae rhamnoides oil',
 'avena sativa kernel oil',
 'buthylphenyl methylpropional',
 'cetearyl acohol',
 'coumarine',
 'cocos nucifera oil',
 'rosa canina fruit oil',
 'punica granatum seed oil',
 'niacinamine',
 'persea gratissima oil',
 'sodium glycerophosphate',
 'potassium magnesium aspartate',
 'calcium glucoheptonate',
 'magnesium gluconate',
 'stearid acid',
 'citirc acid',
 'toopheryl acetate',
 'retinol',
 'mangifera indica fruit extract',
 'rubus idaeus fruit extract',
 'citrus reticulata fruit extract',
 'tocophereyl acetate',
 'rosa moschata oil',
 'prunus amygalus dulcis oil',
 'sodium caprinoyl / lauroyl lactylate',
 'sodium caproyl / lauroyl lactylate',
 'triethylcitrate',
 'plantago lanceolata leaf extract',
 'cydonia oblonga extract',
 'sucrose stearate',
 'arginine',
 'cucumis sativus extract',
 'lilium candidum flower extract',
 'sorbitan olivate',
 'aloe barbandensis leaf extract',
 'propyl gallate',
 'hippophae rhamnoides fruit extract',
 'isocetyl stearate',
 'water/aqua/eau',
 'artemisia vulgaris extract',
 'lavandula angustifolia (lavender) oil',
 'citrus aurantium bergamia (bergamot) fruit oil',
 'butylphenyl methyl propional',
 'hydroxyisohexyl 3-cyclohexene carboxaldehyde',
 'dipropylene glycol',
 'glycereth-26',
 'aloe barbadensis leaf juice',
 'hippophae rhamnoides water',
 'imperata cylindrica root extract',
 'selaginella tamariscina extract',
 'cocos nucifera (coconut)',
 'fruit extract',
 'colloidal oatmeal',
 'persea gratissima (avocado) oil',
 'taraxacum officinale (dandelion)',
 'rhizome/root extract',
 'centaurea cyanus flower extract',
 'magnolia liliflora flower extract',
 'rehmannia glutinosa root extract',
 'sd alcohol 40-b/alcohol denat',
 'musa sapientum (banana) fruit extract',
 'cocos nucifera (coconut) extract',
 'zingiber officinale (ginger) root extract',
 'psidium guajava fruit extract',
 'cymbopogon schoenanthus extract',
 'carica papaya (papaya) fruit extract',
 'maranta arundinacea root extract',
 'rubus idaeus (raspberry) fruit extract',
 'santalum album (sandalwood) extract',
 'macrocystis pyrifera extract',
 'nasturtium officinale extract',
 'aleurites moluccana extract',
 'cucumis sativus (cucumber) fruit extract',
 'sucrose',
 'charcoal*',
 '*activated charcoal',
 'butyrospermum parkii butter / shea butter',
 'polyglyceryl-3 methylglucose distearate',
 'stearyl alcohol',
 'aluminum starch octenylsuccinate',
 'hippophae rhamnoides oil / hippophae rhamnoides fruit oil',
 'hydrolyzed hazelnut protein',
 'malus domestica fruit cell culture extract',
 'capryloyl salicylic acid',
 'glycine soja oil / soybean oil',
 'glycine soja protein / soybean protein',
 'hydrolyzed rice protein',
 'retinyl linoleate',
 'sorbitan tristearate',
 'zea mays starch/corn starch',
 'carrageenan',
 'dextrin',
 'aloe barbadensis leaaf juice powder',
 'vitis vinifera fruit water/grape fruit water',
 'sodium phytate',
 'sodium lauryl sulfate',
 'argania spinosa oil / argania spinosa kernel oil',
 'haematococcus pluvialis / haematococcus pluvialis extract',
 'hexylene glycol',
 'pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate',
 'polyaminopropyl biguanide',
 'disodium cocoamphodiacetate',
 'polysorbate 65',
 'papain',
 'ananas sativus fruit extract / pineapple fruit extract',
 'p-anisic acid',
 'hydrogenated starch hydrolysate',
 'fucus vesiculosus extract',
 'saccharomyces/xylinum/black tea ferment',
 'biotin',
 'centaurea cyanus flower water',
 'coco-betaine',
 'zea mays',
 'starch/corn starch',
 'eucalyptus globulus leaf extract',
 'hydrogenated jojoba oil',
 'smithsonite extract',
 'polyglycerin-10',
 'polyglyceryl-10 myristate',
 'polyglyceryl-10 stearate',
 'sodium dehydroacetate',
 'vaccinium myrtillus fruit extract',
 'propylene glycol dicaprylate/dicaprate',
 'propylene carbonate',
 'serine',
 'tea-lactate',
 'benzophenone-4',
 'cellulose gum',
 'cocamide mea',
 'acer saccharinum extract/sugar maple extract',
 'citrus aurantium dulcis fruit water/orange fruit water',
 'citrus limon fruit extract/lemon fruit extract',
 'ficus carica extract/fig extract',
 'saccharum officinarum extract/sugar cane extract',
 'ficus carica extract/fig exctract',
 'myristyl alcohol',
 'quercus suber bark extract',
 'oak root extract',
 'aloe barbadensis leaf extract',
 'steareth 2',
 'steareth-21',
 'triticum vulgare germ oil',
 'vitis vinfera seed oil',
 'lilial',
 'ammonium lauryl sulfate',
 'melia azadirachta leaf extract',
 'curcuma longa root extract',
 'vetiveria zizanoides root extract',
 'sorbitan stearate',
 'leontopodium alpinum meristem cell culture',
 'cipadessa baccifera flower/leaf/stem extract',
 'rhodomyrtus tomentosa flower/leaf/stem extract',
 'woodfordia fruticosa flower extract',
 'sorbitan',
 'stearate',
 'pyrus malus (apple) fruit extract',
 'cipadessa bacifera flower/leaf/stem extract',
 'zea mays germ oil',
 'hydrolyzed placental protein',
 'zea mays germs oil',
 'cinnamyl alcohol',
 'polygceryl-4 diisostearate/polyhydroxystearate/sebacate',
 'potassium acesulfame',
 'acacia decurrens flower cera/acacua decurrens flower wax',
 'sodium chondroitin sulfate',
 'helianthus annuus seed cera/sunflower seed wax',
 'myristic acid',
 'atelocollagen',
 'adenosine',
 'jojoba esters',
 'hydrolyzed opuntia ficus-indica flower extract',
 'capryly glycol',
 'pentaerythrityl tetraisostearate',
 'polyglycerin-3',
 'prunus armeniaca kernel oil/apricot kernel oil',
 'shorea robusta seed butter',
 'glycine soja protein/soybean protein',
 'faex extract/yeast extract',
 'isopropyl isostearate',
 'aluminum starch ocetenylsuccinate',
 'disodium stearoyl glutamate',
 'oryza sativa bran oil/rice bran oil',
 'cera alba/beeswax',
 'dimethyl isosorbide',
 'arginine pca',
 'fagus sylvatica extract',
 'calcium pca',
 'phloroglucinol trimethyl ether',
 'oryza sativa brain oil/rice brain oil',
 'fagus sylvatica bud extract',
 'iris florentina root extract',
 'butyrospermum parkii butter/shea butter',
 'chamomilla recutita flower extract/matricaria flower extract',
 'urtica dioica extract/nettle extract',
 'equisetum arvense extract',
 'betula alba leaf extract',
 'iris florentina root extraxt',
 'olea europaea oil / olive fruit oil',
 'simmondsia chinensis oil / jojoba seed oil',
 'camelina sativa oil / camelina sativa seed oil',
 'helianthus annuus seed oil / sunflower seed oil',
 'zea mays oil / corn oil',
 'prunus armeniaca kernel oil / apricot kernel oil',
 'passiflora edulis oil / passiflora edulis seed oil',
 'oryza sativa bran oil / rice bran oil',
 'pelargonium graveolens flower oil',
 'citrus aurantium dulcis peel oil / orange peel oil',
 'rosmarinus officinalis leaf oil / rosemary leaf oil',
 'origanum majorana leaf oil',
 'lavandula angustifolia oil / levander oil',
 'anthemis nobilis flower oil',
 'lavandula hybrida oil',
 'cucumis sativus fruit extract / cucumber fruit extract',
 'curcuma longa extract / turmeric root extract',
 'rosa spp / rose flower oil',
 'jasminum officinale extract / jasmine extract',
 'lavandula angustifolia oil / lavender oil',
 'methyl gluceth-20',
 '2-oleamido-1',
 '3-octadecanediol',
 'zea mays oil/corn oil',
 'sesamum indicum oil/sesame seed oil',
 'bifida ferment lysate',
 'ascorbyl glucoside',
 'triticum vulgare germ oil/wheat germ oil',
 'helianthus annuus seed oil/sunflower seed oil',
 'shorea robusta butter/shorea robusta seed butter',
 'ribes nigrum oil/black currant seed oil',
 'rosmarinus officinalis extract / rosemary extract',
 'saccharide hydrolysate',
 'gardenia taitensis flower',
 'euterpe oleracea pulp powder',
 'vitis vinifera seed oil / grape seed oil',
 'haematococcus pluvialis extract',
 'cocos nucifera oil / coconut oil',
 'capsicum annuum extract / capsicum annuum fruit extract',
 'caramel',
 'cera alba / beeswax',
 'copernicia cerifera cera / carnauba wax',
 'citrus aurantium amara flower oil / bitter orange flower oil',
 'limnanthes alba seed oil/meadowfoam seed oil',
 'argania spinosa oil/argania spinosa kernel oil',
 'rosmarinus officinalis leaf oil/rosemary leaf oil',
 'jasminum officinale extract/jasmine flower extract',
 'lavandula angustifola oil/lavender oil',
 'calcium pantothenate',
 'nelumbo nucifera flower extract',
 'rosa gallica flower extract',
 'sodium laureth-8 sulfate',
 'sodium oleth sulfate',
 'magnesium laureth sulfate',
 'magnesium laureth-8 sulfate',
 'magnesium oleth sulfate',
 'oryza sativa starch / rice starch',
 'laminaria saccharina extract',
 'pyridoxine hcl',
 'phenyl ethyl alcohol',
 'faex extract / yeast extract',
 'phenoxy-ethanol',
 'alpinia galanga leaf extract',
 'ceteareth-6',
 'secale cereale extract / rye seed extract',
 'dipotassium glycyrrhizate',
 'secale cereale extract/rye seed extract',
 'ethylhexyl hydroxystearate',
 'capry-loyl salicylic acid',
 'hydroxypropyl tetrahydropyrantriol',
 'hydrolyzed hyaluronic acid',
 'simmondsia chinensis oil/jojoba seed oil',
 'hydrogenated castor oil dimer dilinoleate',
 'centella asiatica extract',
 'palmiti acid',
 'shorea robusta butter / shorea robusta seed butter',
 'zea mays extract / corn kernel extract',
 'salicyloyl phytospingosine',
 'mentha piperita leaf extract',
 'octydodecanol',
 'hydrogenated rapeseed oil',
 'hydrolyzed corn starch',
 'bis-diglyceryl-polyacyladipate-2',
 'candelilla cera',
 'phytosteryl oleate',
 'hydrogenated coco-glycerides',
 'c10-30 cholesterol/lanosterol esters',
 'dibutyl lauroyl glutamide',
 'rubus fruticosus juice',
 'prunus cerasus juice',
 'butyl gratissima oil',
 'hydrolyzed silk',
 'fragaria ananassa fruit juice',
 'cetyl ricinoleate',
 'glyceryl glucoside',
 'ethyl 2-methylbutyrate',
 'allyl caproate',
 'allyl heptanoate',
 'allyl cyclohexylpropionate',
 'gamma-undecalactone',
 'p-menthanone',
 'isoamyl acetate',
 'anisaldehyde',
 'ethyl methylphenylglycidate',
 'ethyl propionate',
 'ethyl hydroxypyrone',
 'butyrospermum parkii butter/shea buttter',
 'avena sativa flour/oat kernel flour',
 'myristyl malate phosphonic acid',
 'oenothera biennis oil / evening primrose oil',
 'isopropyl lauroyl sarcosinate',
 'phenylethyl resorcinol',
 'zinc pca',
 'rosa gallica extract/rosa gallica',
 'flower extract',
 'moringa pterygosperma seed extract',
 'aloe barbadensis leaf juice*',
 'coco-caprylate/caprate',
 'helianthus annuus hybrid oil*',
 'butyrospermum parkii butter*',
 'glyceryl behenate',
 'microcrystalline cellulose',
 'vitis vinifera seed oil*',
 'limonium vulgare flower/leaf/stem extract',
 'c10-18 triglycerides',
 'hydrolyzed adansonia digitata extract',
 'glyceryl behenate glyceryl stearate',
 'polyglyceryl-3 dicitrate/stearate',
 'rosa damascena flower water*',
 'aloe barbadensis leaf extract*',
 'prunus armeniaca fruit extract*',
 'ricinus communis oil',
 'candelilia cera',
 'isopropyl laurate',
 'steareth-2',
 'hexylresorcinol',
 'sodium dodecylbenzenesulfonate',
 'linseed acid',
 'xylitylglucoside',
 'anhydroxylitol',
 'isodecyl neopentanoate',
 'hydroxypropyl starch phosphate',
 'sodium laureth-12 sulfate',
 'isoceteth-10',
 'c11-15 pareth-7',
 'pentaerythrityl tetraethylhexanoate',
 'ppg-15 stearyl ether',
 'palmitoyl oligopeptide',
 'c12-15 alkyl lactate',
 'hamamelis virginiana water',
 'cinnamomum zeylanicum bark extract',
 'cedrus atlantica bark extract',
 'portulaca oleracea extract',
 'sarcosine',
 'cetyl lactate',
 'ppg-2 isoceteth-20 acetate',
 'cocamidopropyl pg-dimonium chloride phosphate',
 'phenethyl',
 'dehydroxanthan gum',
 'benzalkonium chloride',
 'sodium ascorbyl phosphate',
 'cetearyl olivate',
 'c12-14 pareth-12',
 'phenxyethanol',
 'citrus limon peel extract',
 'zea mays starch',
 'c12-14 pareth 12',
 'sodium hyauloronate',
 'sodium hydrolyzed potato starch dodecenylsuccinate',
 'sodium c14-16 olefin sulfonate',
 'cocamidopropyl hydroxysultaine',
 'glycoli acid',
 'sodium cocoyl isethionate',
 'sodium methyl cocoyl taurate',
 'linoleamidopropyl pg-dimonium chloride phosphate',
 'sodium isethionate',
 'sodium c14-16',
 'olefin sulfonate',
 'menthyl lactate',
 'glycolic acid',
 'diisopropyl sebacate',
 'isostearyl isostearate',
 'glyceryl caprylate',
 'disodium tetrapropenyl succinate',
 'rubus chamaemorus fruit extract',
 'glycine soja germ extract',
 'citrate',
 'glycyrrhiza inflata root extract',
 'benzophenone',
 'benzethonium chloride',
 'isopropyl stearate',
 'triisostearin',
 'arachidic acid',
 'oleic acid',
 'creatine',
 'magnolia officinalis bark extract',
 'ppg-26-buteth-26',
 'lauroyl lysine',
 'arginine hcl',
 'distarch phosphate',
 'isobutylamido thiazolyl resorcinol',
 'chondrus crispus extract',
 'butylene glycol dicaprylate/dicaprate',
 'diethylamino hydroxybenzoyl hexyl benzoate',
 'pimpinella anisum fruit extract',
 'ethylhexyl cocoate',
 'macadamia integrifolia seed oil',
 'sodium hyaturonate',
 '2 hexanediol',
 'isosteareth-20',
 'rosa damascena flower water',
 'methyl benzoate',
 'disodium cocoyl glutamate',
 'levulinic acid',
 'sodium levulinate',
 'brassica campestris seed oil',
 'decylene glycol',
 'pantolactone',
 'pathenol',
 'taploca starch',
 'calcium panthothenate',
 'benzyl bezoate',
 'sodium ascorbyl phoshate',
 'silybum marianum seed oil',
 'lanolin alcohol',
 'tridecyl stearate',
 'dipentaerythrityl hexacaprylate/hexacaprate',
 'vitis vinifera (grape) seed oil',
 'helianthus annuus (sunflower) seed oil',
 'biosaccharide gum-4',
 'oryza sativa extract',
 'butyrospemum parkii butter',
 'ceteatyl alcohol',
 'butanediol',
 'dextran',
 'honey',
 'collagen',
 'aloe vera extract',
 'strawberry (fragaria chiloensis ananassa) extract polysorbate-20',
 'hydroxybenzyl',
 'octanoyl hydroxamic acid',
 '100% růžová voda (inci: rosa damascena mill flower extract)',
 'fraxinus excelsior bark extract',
 'panicum miliaceum extract/[panicum miliaceum (millet) seed extract]',
 'coenochloris signiensis extract',
 'olus oil/[vegetable oil]',
 'cera alba/[beeswax]',
 'maltodextrin',
 'tannic acid',
 'potassium citrate',
 'prunus amygdalus dulcis oil (sweet almond oil)',
 'rosa damascena flower oil',
 'butyrospermum parkii (shea butter)',
 'lactobacillus/milk solids/glycine soja (soybean) oil ferment',
 'cyclodextrin',
 'olea europaea (olive) fruit oil',
 'goat milk extract',
 'diisostearoyl polyglyceryl-3 dimer dilinoleate',
 'cera alba (beeswax)',
 'benzyl salycilate',
 'hexyl laurate',
 'sodium cocoamphoacetate',
 'elaeis guineensis (palm) oil',
 'canola oil',
 'sodium starch octenylsuccinate',
 'cocamide dea',
 'monopropylenglycol',
 'lauryl glucoside',
 'ethyl linoleate',
 'helianthus annus (sunflower) seed oil',
 'retinyl acetate',
 'butylhydroxytoluol',
 'cetrimonium chloride',
 'trideceth-10',
 'benzyl salicilate',
 'stearamidopropyl dimethylamine',
 'hydroxypropyl guar',
 'oleyl alcohol',
 'menthae piperita',
 'propylyne glycol',
 'melaleuca alternifolia',
 'sodium saccharin',
 'účinná složka: arginin 8%',
 'citrac acid',
 'sodium xylenesulfonate',
 'glycol distearate',
 'tea-dodecylbenzenesulfonate',
 'sodium salicylate',
 'triethylene glycol',
 'coco glucoside',
 'eucalyptol',
 'methyl salycilate',
 'thymol',
 'methyl salicylate',
 'sucralose',
 'palmitamidopropyltrimonium chloride',
 'ci 77266 (carbon black)',
 'oleth-20',
 'hamamelis virginiana bark/leaf extract',
 'laureth-2',
 'peg-90 glyceryl isostearate',
 'lanolin alcohol (eucerit®)',
 'bambusa vulgaris shoot extract',
 'aminomethyl propanol',
 'sodiumbenzoate',
 'glutamic acid',
 'panthenyl ethyl ether',
 'histidine',
 'trisodium ethylenediamine disuccinate',
 'dimethyl palmitamine',
 'tea-sulfate',
 'trideceth-12',
 'glycerin caprylate',
 'citrus grandis seed extract',
 'cannabis sativa seed extract',
 'glyceryl undecylenate',
 'salvia triloba leaf extract',
 'foeniculum vulgare fruit oil',
 'rosmarinus officinalis leaf oil',
 'thymus vulgaris oil',
 'salvia officinalis oil',
 'disodium laureth sulfosuccinate',
 'olivoyl hydrolyzed wheat protein',
 'tea lauryl sulfate',
 'salvia officinalis leaf extract',
 'thymus vulgaris leaf extract',
 'sodium caproyl/lauroyl lactylate',
 'triethyl citrate',
 'hydrolized rice protein',
 'arnica montana extract',
 'laureth-10',
 'lactose',
 'lactis proteinum',
 'prunus',
 'persica fruit extract',
 'rosa damascena flower extract',
 'magnolia officinalis flower extract',
 'benzophenone-3',
 'farnesol',
 'butlyphenyl methylpropional',
 'alcohol denat',
 'crambe abyssinica seed oil',
 'ppg-20 methyl glucose ether',
 'phenoxethanol',
 'hydroxyitronellal',
 'methyl-2-octynoate',
 'cinnamal',
 'alcohol den.',
 'limonete',
 'farnesol 55% vol.',
 'ethylhexyl methoxycinamate',
 'tributyl citrate',
 'cinamal',
 'aluminum distearate',
 'gloss: ricinus communis seed oil',
 'pentaerythrityl stearate/caprate/caprylate/adipate',
 'laureth-7/laureth-8',
 'glycolipids',
 'butyl acetate',
 'nitrocellulose',
 'acetyl tributyl citrate',
 'isocetyl stearoyl stearate',
 'octyldodecyl stearate',
 'beheneth-30',
 'zinc stearate',
 'glyceryl isostearate',
 'hydrogenated palm kernel glycerides',
 'pyrus malus fruit extract',
 'isostearyl neopentanoate',
 'octyldodecyl stearoyl stearate',
 'lanolin oil',
 'myristyl lactate',
 'licithin',
 'oryza sativa cera',
 'polyglyceryl-4 diisostearate/polyhydroxystearate/sebacate',
 'sucrose tetrastearate triacetate',
 'pentaerythrityl tetrabehenate',
 'isoamyl laurate',
 'acacia senegal gum',
 'trimethyl pentanyl diisobutyrate',
 'glyoxal',
 'copernica cerifera cera',
 'diisostearyl malate',
 'triethylhexanoin',
 'c20-40 alcohols',
 'caprylic/capric trigyceride',
 'prunus amygdalus dulcis fruit extract',
 'magnesium myristate',
 'polyglyceryl-3 beeswax',
 'polyglyceryl-2 sesquiisostearate',
 'glyceryl dibehenate',
 'hydrogenated palm oil',
 'triisodecyl trimellitate',
 'cellulose acetate butyrate',
 'pyrus malus fruit water',
 'aracia senegal gum',
 'evernia prunastri (oakmoss) extract',
 'methyl 2-octynoate',
 'linaool',
 'nirtocellulose',
 'hydroxystearic acid',
 'lemonene',
 'phenoxyethanol ethylhexylglycerin',
 'silk amino acids',
 'malic acid',
 'morus alba root extract',
 'polyglutamic acid',
 'melastoma candidum extract',
 'sucrose acetate isobutyrate',
 'dipropylene glycol dibenzoate',
 'ascorbic acid (vitamin c)',
 'kojic acid',
 'codium tomentosum extract',
 'citrus paradisi (grapefruit) seed extract',
 'cereus grandiflorus (cactus) extract',
 'rhus succedanea fruit cera/rhus succedanea fruit wax',
 'sorbitan palmitate',
 'copernicia cerifera cera/carnauba wax',
 'c12-18 acid triglyceride',
 'ricinus communis oil / castor seed oil',
 'sorbitan distearate',
 'g787587: ricinus communis oil/castor seed oil',
 'candelilla cera/candelilla wax',
 'dipentaerythrityl tetrahydroxystearate/ tetraisostearate',
 'dipentaerythrityl tetrahydroxystearate/tetraisostearate',
 'acacia senegal/acacia senegal gum',
 'polyglyceryl-2 triisostearate',
 'isostearyl sebacate',
 'capryl glycol',
 'ehtylhexylglycerin',
 'isostearate',
 'cocos nucifera oil/coconut oil',
 'ricinus communis oil/castor seed oil',
 'trilaureth-4 phosphate',
 'laureth-21',
 'polyglyceryl-4 isostearate',
 'hydroxyethyl urea',
 'steareth-20',
 'n-hydroxysuccinimide',
 'chrysin',
 'zea mays starch / corn starch',
 'copernica cerifera cera/carnauba wax',
 'pentaerythrityl tetraoisostearate',
 'copernicia cerifera cera/ carnauba wax',
 'acetone',
 'arachidyl behenate',
 'behenic acid',
 'step 2: sucrose polycottonseedate',
 'hydrogenated soybean oil',
 'step 2: surcose',
 'polycottonseedate',
 'octyldoldodecanol',
 'sodium dextran sulfate',
 'disodium stearoyla glutamate',
 'g842584: hydrogenated vegetable oil',
 'g851088: neopentyl glycol',
 'dicaprylate/dicaprate',
 'lanolin liquida / lanolin oil',
 'oleyl erucate',
 'acetylated lanolin',
 'sesamum indicum seed oil / sesame seed oil',
 'sesamum indicum seed oil/sesame seed oil',
 'chamomilla recutita extract / matricaria flower extract',
 'chamomilla recutita extract/matricaria flower extract',
 'diisopropyl dimer dilinoleate',
 'polyglyceryl-2 diisostearate',
 'squalana',
 'lycium barbarum fruit extract',
 'dihydroxyacetone',
 'ceteth-20',
 'laureth-25',
 '2-hexadeniol',
 'aminomethyl propanediol',
 'lauric acid',
 'cera carnauba / carnauba wax',
 'acacia senegal / acacia senegal gum',
 'potassium cetyl phophate',
 'cera/alba/beeswax',
 'acacia senegal/acacia senagal gum',
 'solube collagen',
 'farnesol 51% vol.',
 'isostearic acid',
 'alcohol denat (sd ethyl alcohol 39 c)',
 'cinnamal alcohol',
 'alcohol denat. (sd alcohol 39-c)',
 'butylphenyl methylpropional (lilial)',
 'oryza sativa cera [oryza sativa (rice) bran wax]',
 'elaeis guineensis kernel oil',
 'triethanolamine (and) diethanolamine',
 'cocos nucifera (coconut) oil',
 'isostearyl neopentamoate',
 'alcohol denat. (s.d alcohol 39c)',
 'ethyl hexyl salicylate',
 'alcohol denat. (s.d alcohol 39-c)',
 'hydroxyisohexyl 3-cyclohexene carboxaldehyde (lyral)',
 'cinnamal citral',
 'eugenoll',
 'cinnamyl acohol',
 'n-butyl alcohol',
 'zea mays oil',
 'mustela oil',
 'oenothera biennis oil',
 'chamomilla recutita (matricaria) flower extract',
 'acohol denat. (sd alcohol 39-c)',
 'ethylhexyl methoxylcinnamate',
 'indigofera tinctoria extract',
 'rubus fruticosus (blackberry) juice',
 'sd alcohol 40-b (alcohol denat.)',
 'bezophenone-3',
 'ethylhexyl salicate',
 'hydrolyzed jojoba esters',
 'triacetin',
 'carbon black (nano)',
 'benzophenone-1',
 'diacetone alcohol',
 'corrector: caprylic/capric triglyceride',
 'hydrogenated cocoglycerides',
 'bambusa vulgaris leaf/stem extract',
 'isoamyl cocoate',
 'caprylic/capric glycerides',
 'glyceryl behenate/eicosadioate',
 'oryza sativa starch',
 'laureth-2 benzoate',
 'sodium cocoyl apple amino acids',
 'coconut acid',
 'c12-16 alcohols',
 'palmitoyl myristyl serinate',
 'tromethamine',
 'alcohol pistacia lentiscus gum',
 'mek',
 'sucrose benzoate',
 'acetyl triethyl citrate',
 'pistacia lentiscus gum',
 'formaldehyde',
 'n-buthyl alcohol',
 'isosorbide dicaprylate/caprate',
 'hexanal',
 'panthenyl triacetate',
 'isomalt',
 'rhododendron ferrugineum leaf cell culture extract',
 'maltol',
 'ethyl tosylamide',
 'propyl acetate',
 'camellia oleifera seed oil',
 'nelumbium speciosum flower extract',
 'c12-13 pareth-23',
 'c12-13 pareth-3',
 'oryza sativa cera/rice bran wax',
 'dioxyethanol',
 'phenoxyerhanol',
 'pentaerythityl tetraisostearate',
 'carpylyl glycol',
 'tocofheryl acetate',
 'pentaerythristyl tetraisostearate',
 'phenoxyethaol',
 'propylenecarbonate',
 'bis-diglyceryl polyacylapidate-2',
 'pentaerythrityl tetraisotearate',
 'palmitoyl proline',
 'sodium palmitoyl sarcosinate',
 'magnesium palmitoyl glutamate',
 'palmitic  acid',
 'isonomyl isononanoate',
 'sodium hayluronate',
 'atelcollagen',
 '3-octadodecanediol',
 'bisdiglyceryl polyacyladipate-2',
 'sodium dehydro-acetate',
 'ricinus communis seed oil/castor seed oil',
 'ricinus communis seed oil / castor seed oil',
 'serica powder / silk powder',
 'serica powder/silk powder',
 'nelumbium speciosum extract/nelumbium speciosum flower extract',
 'hydrolyzed  corn starch',
 'sodium chondroidin sulfate',
 'isopropyl titanium triisostearate',
 'royal jelly/royal jelly extract',
 'mel / honey',
 'anise alcohol',
 'mel/honey',
 'octyldodecyl neopentanoate',
 'sodium chondrotin sulfate',
 'atelocoulagen',
 'octyldodecyl neopent anoate',
 'carthamus tinctorius seed oil / safflower seed oil',
 'oryza sativa starch/rice starch',
 'oryza satina cera/rice',
 'ceteareth-33',
 'miristic acid',
 'cocos nucifera fruit extract/coconut fruit extract',
 'galactoarabinan',
 'saccharomyces/ zinc ferment',
 'saccharomyces/calcium ferment',
 'saccharomyces/copper ferment',
 'saccharomyces/iron ferment',
 'saccharomyces/magnesium ferment',
 'saccharomyces/manganese ferment',
 'saccharomyces/potassium ferment',
 'copernicia cerifera cera [copernicia cerifera (carnauba) wax]',
 'lictic acid',
 'aluminum zirconium octachlorohydrex gly',
 'ceasalpinia spinosa gum',
 'gossypium herbaceum (cotton) powder',
 'hydrolyzed wheat protein',
 'mentha piperita (peppermint) oil',
 'gossypium herbacerum (cotton) powder',
 'cetylpyridinium chloride',
 'gossypium herbaceum (cotton) seed extract',
 'sodium ascorbate',
 'guanidine carbonate',
 'methyl pca',
 'ethyl methane carboxamide',
 'vanillyl butyl ether',
 'linoleic acid',
 'potassium gluconate',
 'linolenic acid',
 'guaiacum officinale wood oil',
 'menthyl pca',
 'ethyl menthane carboxamide',
 'ethylhexyl methoxycinnamate linalool',
 'paullinia cupana seed extract',
 'palmatic acid',
 'alcohol denat. 80 % vol.',
 '60% vol. alcohol denat.',
 'propolis extract',
 'tea-stearate',
 'tea-palmitate',
 'laureth-23',
 'aloe barbadensis extract',
 'paullinia cupana fruit extract',
 'mentha aquatica leaf extract',
 'thermus thermophillus ferment',
 'lippia citriodora flower/leaf/stem water',
 'aluminum zirconium tetrachlorohydrex gly',
 'potassium stearate',
 'potassium palmitate',
 'sodium stearate',
 'sodium palmitate',
 'potassium cocoate',
 'sodium cocoate',
 'ethylhexyglycerin',
 'tea-laurate',
 'potassium laurate',
 'steareth-100',
 'alcohol denat. (22 % ob.)',
 'polyglyceryl-3 caprylate',
 'butyloctanoic acid',
 'menthyl acetate',
 'androstadienone',
 'ceteareth- 30',
 'methyl acetate',
 'butyllphenyl methylpropional',
 'cyclohexylethanol',
 'rumex acetosa leaf extract',
 'ceteareth-30',
 '2-benzylheptanol',
 'aluminum zirconium trichlorohydrex gly',
 'coumarin (f.i.l. c49004/1)',
 'menthoxypropanedion',
 'evernia furfuracea extract',
 'alcohol denatured',
 'lavandula angustifolia oil',
 'lauryl alcohol',
 'coceth-7',
 'simmondsia chinensis (jojoba) seed oil',
 'c14-22 alcohols',
 'c12-20 alkyl glucoside',
 'mentha piperita extract/peppermint leaf extract',
 'laminaria digitata extract',
 'magnesium pca',
 'mentha piperita extract/peppermint extract',
 'mannose',
 'betula alba juice',
 'butyrospermum parkii seedcake extract/shea seedcake extract',
 'zinc citrate',
 'maris limus extract',
 'ostrea shell extract',
 'isoceteth-20',
 'laureth-7 citrate',
 'gossypium herbaceum seed oil',
 'laureth-4',
 'sodium myreth sulfate',
 'arctium lappa root powder',
 'isorpopyl palmitate',
 'distarch phophate',
 'triceteareth-4 phosphate',
 'menthoxypropanediol',
 'prg-90 glyceryl isostearate',
 'glycyrrhiza inflata roof extract',
 'silver citrate',
 'ppg-3 myristyl ether',
 'methyl cyclodextrin',
 'foeniculum vulgare (fennel) seed extract',
 'sodium laureth sulfate (a) / sodium c12-13 pareth sulfate (b)*',
 'mentha aquatic leaf extract',
 'rubus idaeus juice',
 'vaccinium myrtillus fruit juice',
 'hydrolysed corn starch octenylsuccinate',
 'aluminium zirconium tetrachlorohydrex gly',
 'ppg-6',
 'humulus lupulus cone extract',
 'ethoxydiglycol',
 'carnitine',
 'taurine',
 'tartaric acid',
 'hydrolyzed keratin',
 'zinc pyrithione',
 'hydrolyzed corn starch octenylsuccinate',
 'ceramide np',
 'steardimonium hydroxypropyl hydrolyzed keratin',
 'sodium lauroyl methyl isethionate',
 'sodium methyl isethionate',
 'zinc laurate',
 'laurtrimonium chloride',
 'sine adipe lac/nonfat dry milk/poudre de lait ecreme',
 'euterpe oleracea fruit extract',
 'aesculus hippocastanum seed extract',
 'rosmarinus officinalis oil',
 'camphor',
 'abies sibirica needle oil',
 'arnica montana flower extract',
 'c12-15 pareth-2',
 'symphytum officinale root extract',
 'pinus sylvestris twig leaf oil',
 'beheneth-10',
 'zingiber officinale root extract',
 'eugenia caryophyllus leaf oil',
 'thymus vulgaris extract',
 'lavandula angustifolia flower extract',
 'rosa centifolia flower extract',
 'sodium glutamate',
 'hydrolyzed milk protein',
 'hydroxypropyltrimonium hydrolyzed casein',
 'sodium cocoyl',
 'glutamate',
 'olea europaea oil',
 'ceteareth-25',
 'prunus amygdaulus dulcis oil',
 'ceteareh-20',
 'potassium lactate',
 'sodium stearoyl lactylat',
 'sunflower seed oil polyglyceryl-6 esters',
 'ricinus communis (castor) seed oil',
 'vaccinium macrocarpon (cranberry) seed oil',
 'avena sativa (oat) kernel extract',
 'bellis perennis (daisy) flower extract',
 'sodium stearoyl lactylate',
 'eriophorum spissum flower/stem extract',
 'hydrogenated lecithin',
 'aesculus hippocastanium extract',
 'eucalyptus leaf extract',
 'symphytum officinale',
 'root extract',
 'dimethyl sulfone',
 'rosmarinus officinalis extract',
 'boswellia serrata extract',
 'aesculus hippocastanum extract',
 'caprylate.',
 'bees wax',
 'centrimonium chloride',
 'pentytene glycol',
 'dimethyl phenylpropanol',
 '2-methyl-5-cyclohexylpentanol',
 'abies sibirica oil',
 'capsicum annuum extract',
 'alcohol ddenat.',
 'capsicum frutescens resin',
 'citrus grandis peel oil',
 'citrus aurantium dulcis oil',
 'cucumis melo fruit water',
 'prunus lannesiana flower extract',
 'menthyl ethylamido oxalate',
 'trimethylcyclohexyl butylcarbamate',
 'sodium lauroyl glycinate',
 'sodium lauroyl isethionate',
 'ppg-2 hydroxyethyl cocamide',
 'sodium lauroyl glutamate',
 'iodoporpynyl butylcarbamate',
 'peg-4 laurate',
 'sodium laurate',
 'glycol stearate',
 'helianthus annuus hybrid oil',
 'isomerized linoleic acid',
 'stearamide amp',
 'cocomidopropyl betaine',
 'sodium hydroxypropyl starch phosphate',
 'capric acid',
 'caprylic acid',
 'punica granatum seed powder',
 'sodium palm kernelate',
 'healianthus annuus seed oil',
 'porpylene carbonate',
 'prunus amygdalus dulcis seed extract',
 'sine adipe lac',
 'prunus amygdalus dulcis seed extrakt',
 'iosopropynyl butylcarbamate',
 'hexyl cinnaml',
 'lavendula angustifolia flower extract',
 'rosmarinus officinalis leaf extract',
 'oryza sativa bran extract',
 'oryza sativa germ oil',
 'cocoamidopropyl betaine',
 'macadamia intergrifolia/tetraphylla seed oil',
 'oryza sativa (rice) bran extract',
 'oryza sativa (rice) germ oil',
 'glyceryl sterate',
 'helianthus anuus seed oil',
 'collagen amino acids',
 'nonfat dry milk',
 'sorbitan monooleate',
 'linallol',
 'silk powder',
 'cocos nucifera fruit extract',
 'prunus amygdalus amara kernel oil',
 'trideceth-7',
 'prunus serrulata flower extract',
 'honey extract',
 'avena sativa kemel extract',
 'punica granatum fruit juice',
 'hibiscus sabdariffa flower extract',
 'glycine soja (soybean) oil',
 'theobroma cacao (cocoa) seed butter',
 'zea mays (corn) starch',
 'cholesterol',
 'centella asiatica leaf extract',
 'hedera helix leaf extract',
 'laminaria hyperborea extract',
 'euglena gracilis extract',
 'glaucium flavum leaf extract',
 'castanea sativa seed extract',
 'globularia cordifolia callus culture extract',
 'zingiber zerumbet extract',
 'carnitine hcl',
 'phosphatidylcholine',
 'butyl alcohol',
 'kigelia africana leaf extract',
 'astrocaryum murumuru seed butter',
 'yogurt',
 'aleurites moluccanus seed oil',
 'calophyllum inophyllum seed oil',
 'laureth-11',
 'leptospermum petersonii oil',
 'hexyl cinnamal (f.i.l. c184515/2)',
 'aloe babadensis leaf juice',
 'hydroxysiohexyl 3-cyclohexene carboxaldehyde',
 'zelená: sodium benzoate',
 'beta-glucan',
 'juniperus communis fruit oil',
 'gelidium cartilagineum extract',
 'propylene glycol diethylhexanoate',
 'rosmarinus officinalis flower oil',
 'aesculus hippocastanum fruit extract',
 'cinnamomum zeylanicum bark oil',
 'hamamelis virginiana leaf extract',
 'ribes nigrum leaf extract',
 'scutellaria baicalensis extract',
 'ruscus aculeatus root extract',
 'cannabis sativa leaf/stem extract',
 'abies alba leaf oil',
 'echinacea purpurea extract',
 'agrimonia eupatoria extract',
 'pinus pumila twig leaf oil',
 'polygonum bistorta root extract',
 'citrus limon fruit oil',
 'pinus mugo twig oil',
 'calluna vulgaris extract',
 'ribes nigrum fruit extract',
 'capsicum frutescens fruit extract',
 'olea europea fruit oil',
 'plukenetia volubilis seed oil',
 'laureth-30',
 'c10-c18 triglyceride',
 'calendula officinalis extract',
 'tocoferyl acetate',
 'allantoin calcium pantothenate',
 'vitis vinifera seed extract',
 'actinidia chinensis (kiwi) fruit juice',
 'c12-13 alkyl lactate',
 'prunus persica (peach) juice',
 'citrus paradisi (grapefruit) juice',
 'rosa moschata seed oil',
 'calcium pantotenate',
 'helianthus anuus (sunflower) seed oil',
 'tripropylene glycol',
 'sodium tallowate',
 'limetka: laureth-7',
 'pomeranč: laureth-7',
 'jahoda: laureth-7',
 'sodium palm kernelate (or) sodium cocoate',
 'cedrus atlantica (cedar) oil',
 'pogostemon cablin (patchouli) oil',
 'lavandula hybrida (lavandin) oil',
 'etidronic acid',
 'cupressus sempervirens (cypress) oil',
 'coriandrum sativum seed oil/coriander seed oil',
 'glycine soja oil/soybean oil',
 'ribes nigrum seed oil/black currant seed oil',
 'avena sativa kernel extract/oat kernel extract',
 'cetearyl wheat straw glycosides',
 'sorbitan laurate',
 'aloe barbadensis leaf extract**',
 'citrus aurantium amara flower water**',
 'ficus carica fruit extract**',
 'hibiscus sabdariffa flower extract**',
 'ficus carica fruit extract*',
 'hibiscus sabdariffa flower extract*',
 'salvia officinalis leaf water**',
 'thymus vulgaris leaf extract**',
 'salvia officinalis leaf water*',
 'thymus vulgaris leaf extract*',
 'citrus aurantium amara flower water*',
 'gylcol distearate',
 'steareth-25',
 'ethyl oleate',
 'ethyl linolenate',
 'macadamia integrifolia/tetraphylla seed oil',
 'sodium palmate',
 'palm acid',
 'cocoyl methyl glucamide',
 'palm kernel acid',
 'elaeis guineensis oil',
 'sesamum indicum seed oil',
 'leontopodium alpinum extract',
 'caprylhydroxamic acid',
 'histidine hcl',
 'threonine',
 'lysine hcl',
 'alanine',
 'glycyrrhiza glabra root extract',
 'pca',
 'citrulline',
 'polyglyceryl-2 dipolyhydroxystearate',
 'persea grattisima oil',
 'cymbopogon citratus extract',
 'bonzoic acid',
 'polyglyceryl-3 distearate',
 'linelool',
 'nelumbo nucifera leaf extract',
 'polyglyceryl-2 caprate',
 'benzyl salicytate',
 'gardenia taitensis flower extract',
 'prunus persica juice',
 'sodium c12-13 pareth sulfate (*a) / sodium laureth sulfate (*b)',
 'vanilla planifolia extract',
 'sodium palmate *a',
 'sodium tallowate *b',
 'lactis serum proteinum',
 'mel',
 'rosa damascena extract',
 'prunus amygdalus sulcis fruit extract',
 'ribes nigrum juice',
 'distearyldimonium chloride',
 'mentha arvensis leaf oil',
 'propylenglycol',
 'aesculus hippocastanum etract',
 'vitis vinifera leaf extract',
 '100% tuk ze semen máslovníku afrického (vitellaria nilotica) z kontrolovaného ekologického zemědělství',
 'melaleuca alternifolia leef oil',
 'cymbopogon flexuosus leaf oil',
 'hydrogen starch hydrolysate',
 'steareth-4',
 'nymphaea alba root extract',
 'hylocereus undatus fruit extract',
 'disodium lauryl phenyl ether disulfonate',
 'hydrolized silk',
 'whey protein',
 'thymus vulgaris (thyme) flower / leaf extract',
 'rosmarinus officinalis (rosemary) leaf extract',
 'sodium alkyl ethoxy sulphate',
 'hydrolysed corn starch',
 'hydroxycitronellol',
 'orchis mascula extract',
 'cinannamyl alcohol',
 'keratin',
 'potassium thioglycolate',
 'beheneth-25',
 'sodium gluconate',
 'aluminum/magnesium hydroxide stearate',
 'cetearyl alchohol',
 'butylphenyt methylpropional',
 'abies alba needle oil',
 'pinus mugo pumilio twig/leaf oil',
 'gentiana lutea root extract',
 'veronica officinalis leaf extract',
 'althea officinalis root extract',
 'malva sylvestris flower extract',
 'methyl nicotinate',
 'eugenia caryophyllus flower oil',
 'avena sativa straw extract',
 'castrol oil',
 'ethanol',
 'sodium cocaamphoacetate',
 'amonomethyl propanol',
 'bezophenone-4',
 'terminalia ferdinandiana fruit extract',
 'jasminum officinale flower/leaf extract',
 'prunus serotina bark extract',
 'ecklonia radiata extract',
 'oryza sativa (rice) starch',
 'geratinol',
 'cyamopsis tetragonolobus gum',
 'celulose gum',
 'zea mays gluten protein',
 'sodium coco-glucoside tartrate',
 'urtica urens leaf extract',
 'zingiber officinale root oil',
 'hyssopus officinalis leaf oil',
 'decyl myristate',
 'citronelloíl',
 'behentrimonium chloride',
 'trideceth-6',
 'camellia sinensis (green tea) leaf extract',
 'mipa-lauryl sulfate',
 'rosmarinus officinalis (rosemary) extract',
 'salvia officinalis flower/leaf/stem extract',
 'cetyl esters',
 'ethanolamine',
 '4-diaminophenoxyethanol hci',
 'm-aminophenol',
 'cemellia oleifera seed oil',
 'p-phenylenediamine',
 'resorcinol',
 'erythorbic acid',
 'trideceth-2 carboxamide mea',
 'triedeceth-6',
 'isostearyl alcohol',
 'resorcional',
 '4-amino-2-hydroxytoluene',
 'thiolactic acid',
 'p-aminophenol',
 '2-amino-3-hydroxypyridine',
 '2-methylresorcinol',
 '2-methyl-5-hydroxyethylaminophenol',
 'saccharum officinarum extract / sugar cane extract',
 'cocos nucifera fruit juice / coconut fruit juice',
 'hydroxypropyltrimonium lemon protein',
 'pyrus malus fruit extract / apple fruit extract',
 'citrus limon peel extract / lemon peel extract',
 'leuconostoc/radish root ferment filtrate',
 'steareth-6',
 'acetic acid',
 'trideceth-3',
 'fumaric acid',
 'pyrus malus fruit extract/apple fruit extract',
 'vitis vinifera seed extract/grape seed extract',
 'citrus limon peel extract/lemon peel extract',
 'punica granatum extract',
 'hydrolyzed vegetable protein pg-propyl silanetriol',
 'phyllanthus emblica fruit extract',
 'simmondsia chinensis seed oil/jojoba seed oil',
 'prunus amygdalus dulcis oil/sweet almond oil',
 'saccharin officinarum extract/sugar cane extract',
 'leuconostic/radish root ferment filtrate',
 'carica papaya fruit extract/papaya fruit extract',
 'distearoylethyl hydroxyethylmonium methosulfate',
 'prunus armeniaca (apricot) kernel oil',
 'behentrionium chloride',
 'magnesium citrate',
 'trideceth-5',
 'behenoyl pg-trimonium chloride',
 'paeonia lactiflora root extract',
 'ppg-1 trideceth-6',
 'argania spinosa shell powder',
 'orbignya oleifera seed oil',
 'cera alba (beeswax',
 'cire ďabeille)',
 'cera carnauba (copernicia cerifera (carnauba) wax',
 'cire de carnauba)',
 'laurdimonium hydroxypropyl hydrolyzed wheat protein',
 'sclerocarya birrea seed oil',
 'hexyl salicylate',
 'cetyl ethylhexanoate',
 'dimethyl ether',
 'citronello',
 'oleth-10',
 'ceteth-2',
 'corn starch modified',
 'dicetyl phosphate',
 'ceteth-10 phosphate',
 'charcoal extract',
 'behentrimoniumchloride',
 'henna',
 'cetrimonium methosulfate',
 'stearoxypropyl dimethylamine',
 'c14-28 isoalkyl acid',
 'succinic acid',
 'c14-28 alkyl acid',
 'vitis vinifera juice extract',
 'helianthus annuus seed extract',
 'ppg-9',
 'crocus sativus flower extract',
 'laureth-16',
 'triedeceth-12',
 'amp-isostearoyl hydrolyzed wheat protein',
 'musa sapientium fruit extract',
 'maltodextrin sodium starch',
 'octenylsuccinate silica',
 'distearyl ether',
 'maltrodextrin sodium starch',
 'linum usitatissimum seed oil',
 'linum usitatissium seed oil',
 'hydrolyted keratin',
 'citrus sinensis extract',
 'citrus limon extract',
 'laureth-5 carboxylic acid',
 'cocamide mipa',
 'xylose',
 'linum usitatissimum flower extract',
 'gardenia tahitensis flower extract',
 'rosa canina flower extract',
 'hexygene glycol',
 'hydroxypropyltrimonium hydrolyzed wheat protein',
 'leureth-4',
 'glyceryl linolenate',
 'diethylhexyl sodium sulfosuccinate',
 'cyamopsis tetragonolobus gum / guar gum',
 'sodium carboxymethyl starch',
 '3-octadecandiol',
 'dipalmitoyethyl hydroxyethylmonium methosulfate',
 'dipalmitoylethyl hydroxyethylmonium methosulfate',
 'methyl cocoate',
 'potato starch modified',
 'linum usitatissimum flower extract/linseed flower extract',
 'linum usitatissimum flower extract / linseed flower extract',
 'starch acetate',
 'dicetyldimonium chloride',
 'hydrolyzed oats',
 'deceth-3',
 'laureth-12',
 'oleth-30',
 'toluene-2',
 '5-diamine',
 '4-diaminophenoxyethanol hcl',
 'thioglycerin',
 'proline',
 'hibiscus sabdariffa extract / hibicus sabdariffa flower extract',
 'candelilla cera / candelilla wax',
 'ammonium thiolactate',
 'hibiscus sabdariffa extract/hibiscus sabdariffa flower extract',
 'hibiscus sabdariffa extract / hibiscus sabdariffa flower extract',
 'glyceryl lauryl ether',
 'disodium cocoamphodipropionate',
 'polyglyceryl-4 oleyl ether',
 'polyglyceryl-2 oleyl ether',
 'sodium diethylaminopropyl cocoaspartamide',
 'ammonium acetate',
 'camelina sativa oil/camelina sativa seed oil',
 'cetrimonium chlorodie',
 'olea europaea fruit oil*',
 'polyglyceryl-4 caprate',
 'polyglyceryl-3 ricinoleate',
 'ocimum basilicum leaf extract*',
 'olea europaea fruit extract*',
 'brassicamidopropyl dimethylamine',
 'cetaaryl alcohol',
 'bis-(isostearoyl/oleoyl isopropyl) dimonium methosulfate',
 'cetearyl  alcohol',
 'isopropyl  alcohol',
 'methosulfate',
 'triticum vulgare (wheat) starch',
 'disodium lauryl sulfosuccinate',
 'sodium anisate',
 'acacia farnesiana flower extract',
 'hydroxyethyl cetyldimonium phosphate',
 'benzo-phenone-4',
 'c12-15 pareth-3',
 'hyrolyzed milk protein',
 'laureth-9',
 'undecylenamidopropyl betaine',
 'melissa officinalis leaf extract',
 'nymphaea odorata root extract',
 'staramidopropyl dimethylamine',
 '2-amino-4-hydroxyethylaminoanisole sulfate',
 '6-methoxy-2-methylamino-3-aminopyridine hci',
 'triticum vulgare starch',
 'calcium stearate',
 '6-dicarboxypyridine',
 'coconut alcohol',
 'ppg-2 hydroxyethyl coco/isostearamide',
 'dodecylbenzene sulfonic acid',
 'behentrimonium methosulfate',
 'triethyl',
 'glycine soja seed extract',
 'behenamidopropyl dimethylamine',
 'fragaria vesca (strawberry) fruit extract',
 'musa paradisiaca (banana) fruit juice',
 'salvia hispanica seed extract',
 'actinidia chinensis (kiwi) fruit extract',
 'nymphaea caerulea flower extract',
 'lavandula angustifolia (lavender) flower extract',
 'satureja montana extract',
 'origanum vulgare leaf extract',
 'thymus vulgaris (thyme) leaf extract',
 'mel (honey extract',
 'extrait de miel)',
 'opuntia ficus-indica seed oil',
 'hippophae rhamnoides fruit juice',
 'magnesium chloride biotin',
 'sodium laureth-6 carboxylate',
 'butyloctanol',
 '4-chlororesorcinol',
 'steartrimonium chloride',
 'cocodimonium hydroxypropyl hydrolyzed keratin',
 'ceteareth-50',
 'sodium lauryl glucose carboxylate',
 'litchi chinensis fruit extract',
 'morinda citrifolia fruit extract',
 'triethyl hexanoin',
 'caprilic/capric triglyceride',
 'sodium chloride-laureth-2',
 'bezyl salicylate',
 'isopopropyl alcohol',
 'n-bis(2-hydroxyethyl)-p-phenylendiamine sulfate',
 'bertholletia excelsa seed oil',
 'ethenolamine',
 'cetaryl alcohol',
 'dicaprypyl carbonate',
 'buthylhenyl methylpropional',
 'behentrimonium chlorid',
 'benzoate',
 'argania apinosa kernel oil',
 'caprylyl/capryi glucoside',
 'cocosimonium hydroxypropyl hydrolyzed keratin',
 '6-dicarboxypyridine. disodium pyrophosphate',
 'opuntia ficus-indica flower extrat',
 'opuntia ficus-indica flower extract',
 'opuntia ficus-indica flower',
 'extract',
 'xylitylglucosside',
 'aminomethylpropanol',
 'stearamidopropyl dimethylamide',
 'sodium cetearyl sufate',
 'sodium cetearyl  sulfate',
 'ampd-isostearoyl hydrolyzed collagen',
 'tetrahydroxypropyl ethylenediamine',
 'coumarin  benzyl alcohol',
 'distraroylethyl hydroxyethylmonium methosulfate',
 'chitosan',
 'glycosphingolipids',
 'hydrogenated ethylhexyl olivate',
 'hydrogenated olive oil unsaponifiablec',
 'stearamidoropyl dimethylamine',
 'cocoyl hydrolyzed keratin',
 'ethylexylglycerin',
 'gluconic acid',
 'benzoic alcohol',
 'benzophene-4',
 'bambusa vulgaris leaf/stem extrakt',
 'bambusa vulgaris extract',
 'betula alba extract',
 'urtica dioica extract',
 'adipic acid',
 'ctronellol',
 'oleth-5',
 'lanolin cera (lanolin wax)',
 'aluminum strach octenylsuccinate',
 'coumain',
 'distearate',
 'tea-dodecylbenzensulfonate',
 'sorbitan butylcarbamate',
 'guar hydroxypropyl trimonium chloride',
 'cintronellol',
 'propylene glycol dibenzoate',
 'lactin acid',
 'peg-7 propyheptyl ether',
 'butylphenyl methyl-propional',
 'aloe barbadensis (aloe vera) leaf juice powder',
 'cocos nucifra (coconut) fruit extract',
 'sine adipe lac (nonfat dry milk)',
 'cocos nucifera (coconut) fruit extract',
 'glycol',
 'undeceth-11',
 'undeceth-5',
 'opuntia ficus-indica extract',
 'ammonium benzoate',
 'lauryl pyrrolidone',
 'opunta ficus-indica (cactus) extract',
 'ammonium thioglycolate',
 'arctium lappa root extract',
 'plantago major leaf extract',
 'citri acid',
 'cellulose gum (20%)',
 'commiphora myrrha oil',
 'citrus limon peel oil',
 'sodium lauryl sulphate',
 'bromelain',
 'salvadora persica stem extract',
 'prunus amygdalus dulcis shell extract',
 'eugenia caryophyllus bud oil',
 'sodium sacharin',
 'punica granatum bark ext.',
 'zanthoxylum alatum fruit ext.',
 'acacia arabica sten bark ext.',
 'terminalia chebula fruit ext. & terminalia bellerica fruit ext. & emblica officinalis fruit ext.',
 'embelia ribes fruit ext.',
 'melia azadirachta leaf ext.',
 'vitex negundo ext.',
 '-diol limonene',
 'aluminium lactate',
 'salvadora persica bark extract',
 'peg-6',
 'chondrus crispus (carrageenan)',
 'mentha arvensis herb oil',
 'mentha cardiaca herb oil',
 'mentha spicata herb oil',
 'thymus vulgaris flower/leaf oil',
 'petroselinum crispum leaf oil',
 'chamomilla recutita flower water',
 'zinc lactate',
 'steviol glycosides',
 'cocamidopropyl. betaine',
 'steareth- 30',
 'amyloglucosidase',
 'glucose oxidase',
 'lysozyme',
 'lactoferrin',
 'lactoperoxidase',
 'vaječný a mléčný protein',
 'steareth-30']

other= [' ceresin',
 ' paraffinum liquidum',
 ' parfum',
 ' silica dimethyl silylate',
 '(daily) flavor',
 '(f.i.l. c46441/1)',
 '(methyl-',
 '* a/b: viz výrobní kód',
 '* ingredience z organického zemědělství',
 '**ingredience z organického zemědělství',
 '*a/b: viz výrobni kód',
 '*a/b: viz výrobní kód',
 '*ingredience z organického zemědělství',
 '+/- (may contain): ci 77499 (iron oxides)',
 '+/- ci 12085',
 '+/- ci 15850',
 '+/- ci 45410',
 '+/- ci 75470',
 '+/- ci 77266',
 '+/- ci 77491',
 '+/- ci 77492',
 '+/- ci 77499',
 '+/- ci 77891',
 '+/- synthetic fluorphlogopite',
 '+/-: ci 42090',
 '+/-: ci 77491',
 '+/-: ci 77492',
 '+/-: ci 77499',
 '+/-: ci 77891',
 '+/-: ci 77891. ci 77492. ci 77491',
 '+/-ci 77891',
 '0 % hm.',
 '00 %',
 '00 % hm. max.',
 '00 % hm.!',
 '1',
 '1 wax: paraffinum liquidum',
 '1-hydroxyethyl 4',
 '1-methylhydantion-2-imide',
 '1-methylhydantoin- 2-imide',
 '1-methylhydantoin-2-imide',
 '1-naphthol',
 '1-naphthol-4-amino-2-hydroxytoluene',
 '1-naphtol',
 '14% f)',
 '15850',
 '15985',
 '2',
 "2'-methylenebis-4-aminophenol hcl",
 '2-(4-terc-butylbenzyl) propanal',
 '2-amino-3- hydroxypyridine',
 '2-amino-4-hydroxyethlyaminoanisole sulfate',
 '2-amino-6-chloro-4-nitrophenol',
 '2-amino-6chloro-4-nitrophenol',
 '2-amoni-6-chloro-4-nitrophenol',
 '2-bromo-2-nitropropane- 1',
 '2-bromo-2-nitropropane-1',
 '2-bromo-2-nitropropene-1',
 '2-diol',
 '2-methyl-5-hydroyethylaminophenol',
 '22% w/w (1000 ppm f¨)',
 '3',
 '3 % hm.',
 '3-bis-(2',
 '3-diol',
 '3-dioxane',
 '3-nitro-p-hydroxyethylaminophenol',
 '32% w (1450 ppmf")',
 '4- trihydroxybenzene',
 '4-amino-3-nitrophenol',
 '4-amino-hydroxytoluene',
 '4-amino-m-cresol',
 '4-diaminophenoxy) propane hci',
 '4-diaminophenoxy) propane hcl',
 '4-diaminophenyl)propane hcl',
 '4-hydroxypropylamino-3-nitrophenol',
 '4-terpineol',
 '45380',
 '45410',
 '5-amino-6-chloro-o-cresol',
 '5-amino-chloro-o-cresol',
 '5-bromo-5-nitro-1',
 '5-diame sulfate',
 '5-diamine sulfate',
 '5-diamino pyrazole sulfate',
 '5-diamo pyrazole sulfate',
 '6 dicarboxypyridine',
 '6-hydroxyindole',
 '6-methoxy-2-methylamino-3-aminopyridine hcl',
 '7-naphthalenediol',
 '74160',
 '77491',
 '77492',
 '77499',
 '79% v / v',
 '80% vol',
 '[+/- ci 12085',
 '[+/- ci 15850',
 '[+/- ci 77891',
 '[+/- may contain',
 '[+/- may contain / peut contenir ci 19140 / yellow 5',
 '[+/- may contain ci 7741',
 '[+/- may contain ci 77491',
 '[+/- may contain ci 77510 / ferric ferrocyanide',
 '[+/- may contain ci 77891 / titanium dioxide',
 '[+/- may contain ci 77891/titanium dioxide',
 '[+/- may contain ci77491',
 '[+/- may contain/peut contenir ci 19140/yellow 5',
 '[+/- may contain:  ci 77891 / titanium dioxide',
 '[+/- may contain: ci 45410/red 28 lake',
 '[+/- may contain: ci 77491',
 '[+/- may contain: ci 77499',
 '[+/- may contain: ci 77499 / iron oxides]',
 '[+/- may contain: ci 77499/iron oxides',
 '[+/- may contain: ci 77499/iron oxides]',
 '[+/- may contain: ci 77891 / titanium dioxide',
 '[+/- may contain: ci 77891/titanium dioxide',
 '[+/-may contain: ci 77891/titanium dioxide',
 '[may contain/peut contenir/+/-: iron oxides (ci 77491',
 '[may contain/peut contenir/+/-: titanium dioxide (ci 77891)',
 '[may contain/peut contenir:/+/-: titanium dioxide (ci 77891)',
 '[may contain: ci 77491',
 'acetum',
 'acetyl trifluoromethylphenyl valyglycine',
 'acetyl trifluoromethylphenyl valylglycine',
 'acid violet 43',
 'adeps bovis',
 'admodimethicone',
 'alpa-isomethyl ionone',
 'alpha iso methyl ionone',
 'alpha isomethyl ionone',
 'alpha-isomethyl ionone',
 'alpha-isomethyl-ionone',
 'alphaisomethyl ionone',
 'aminopropyl dimethicone',
 'aminopropyl triethoxysilane',
 'amodimethicone',
 'amooimethicone',
 'anethole',
 'apha-isomethyl ionone',
 'aplha-isomethyl ionone',
 'aqua (and) ci 77266',
 'aqua-isomethyl ionone',
 'aroma',
 'arunika ekisu',
 'base coat: isododecane',
 'basic brown 17',
 'basic orange 31',
 'basic red 51',
 'basic red 76',
 'basic violet 2',
 'basic yellow 57',
 'basic yellow 87',
 'benzotriazolyl dodecyl p-cresol',
 'benzotrizolyl dodedecyl p-cresol',
 'bha',
 'bht',
 'biosaccharide gum-1',
 'bis (hydroxymethyl)',
 'bis-aminopropyl dimethicone',
 'bis-behenyl/isostearyl/phytosteryl dimer dilinoleyl dimer dilinoleate',
 'bis-cetearyl amodimethicone',
 'bis-ethylhexyloxyphenol methoxyphenyl triazine',
 'bis-peg/ppg-14/14 dimethicone',
 'blue 1 (ci 42090)',
 'bran wax',
 'butane',
 'butane-isobutane-propane',
 'buteth-3',
 'butyl crbamate chips: diol',
 'butyl methoxydibenzoyl methane',
 'butyl methoxydibenzoylmethane',
 'butylmethoxydibenzoylmethane',
 'butylparaben',
 'butylphenyl',
 'butylphenylmethylpropional',
 'butyphenyl metylpropional',
 'c. i. 18050',
 'c.i. 12085',
 'c.i. 14700 (food red 1)',
 'c.i. 14720',
 'c.i. 18050',
 'c.i. 19140',
 'c.i. 19140 (acid yellow 23)',
 'c.i. 42045 (acid blue 1)',
 'c.i. 42090',
 'c10-11 isoparaffin',
 'c11-12 isoparaffin',
 'c11-13 isoparaffin',
 'c13-14 isoparaffin',
 'c15-19 alkane',
 'c15-19 alkane&diphenyl dimethicone',
 'c20-24 alkyl dimethicone (and) c20-24 olefin',
 'c20-40 acid',
 'c30-45 alkyl dimethicone',
 'c30-45 alkyl methicone',
 'c30-45 olefin',
 'c8-9 isoparaffin',
 'c9-13 isoparaffin',
 'c9-15 fluoroalcohol phosphates / c9-15 fluoeoalcohol phosphate',
 'c9-15 fluoroalcohol phosphates/c9-15 fluoralcohol phosphate',
 'c9-15 fluoroalcohol phosphates/c9-15 fluoroalcohol',
 'calcium disodium edta',
 'calcium pantetheine sulfonate',
 'caprylyl methicone',
 'carboxymethyl',
 'carnosine',
 'cellulose acetate',
 'cera microcrisrallina/microcrystalline wax',
 'cera microcristalina / microcrystalline wax',
 'cera microcristallina',
 'cera microcristallina (microcrystalline wax',
 'cera microcristallina (microcrystalline wax)',
 'cera microcristallina / microcrystalline wax',
 'cera microcristallina / mikrocrystalline wax',
 'cera microcristallina/microcrystalline wax',
 'cera microcristallina/microcrytalline wax',
 'cera microcristalline',
 'cera microcristaluna / microcrystalline wax',
 'cera microcrystallina',
 'ceresin',
 'cetyl diglyceryl dris (trimethylsiloxy)silylethyl dimethicone',
 'cetyl diglyceryl tris (trimethylsiloxy) silylethyl dimethicone',
 'cetyl diglyceryl tris (trimethylsiloxy)silylethyl dimethicone',
 'cetyl dimethicone',
 'cetyl hydroxy-ethylcellulose',
 'cetyl hydroxyethylcellulose',
 'chlorhexidine',
 'chlorhexidine digluconate',
 'chlorhexidine dihydrochloride',
 'chlorophenesin',
 'chlorphenesin',
 'chondrus crispus powder',
 'ci  77400/copper powder',
 'ci 10316',
 'ci 11680',
 'ci 12085',
 'ci 14700',
 'ci 14700 (fd&c red 4)',
 'ci 14700 (red 4)',
 'ci 14700 / red 4',
 'ci 14700/red 4',
 'ci 14720',
 'ci 14815',
 'ci 15510',
 'ci 15850',
 'ci 15850 / red',
 'ci 15850 / red 6',
 'ci 15850 / red 6 lake',
 'ci 15850 / red 7',
 'ci 15850 / red 7 lake',
 'ci 15850 / red 7 lake]',
 'ci 15850 / red 7]',
 'ci 15850/red 6',
 'ci 15850/red 6 lake',
 'ci 15850/red 7',
 'ci 15850/red 7 lake',
 'ci 15850/red 7 lake]',
 'ci 15850/red 7]',
 'ci 15850:1',
 'ci 15880',
 'ci 15880 / red 34 lake',
 'ci 15880/red 34 lake',
 'ci 15985',
 'ci 15985 (sunset yellow aluminium lake)',
 'ci 15985 (yellow 6)',
 'ci 15985 / yellow 6',
 'ci 15985 / yellow 6 lake',
 'ci 15985/yellow 6',
 'ci 15985/yellow 6 lake',
 'ci 16035',
 'ci 16035 (red 40)',
 'ci 16035/red 40 lake',
 'ci 16185',
 'ci 16225',
 'ci 16238',
 'ci 16255',
 'ci 162557',
 'ci 16570',
 'ci 17200',
 'ci 17200 (fc&c red n° 33)',
 'ci 17200 (red 33)',
 'ci 17200 / red 33',
 'ci 17200 / red 33 lake',
 'ci 17200/red 33',
 'ci 17200/red 33 lake',
 'ci 18050',
 'ci 19 140',
 'ci 19140',
 'ci 19140 (fd&c yellow 5)',
 'ci 19140 (yellow 5)',
 'ci 19140 / yellow 5',
 'ci 19140 / yellow 5 lake',
 'ci 19140/yellow 5',
 'ci 19140/yellow 5 lake',
 'ci 19140/yellow 5 lake]',
 'ci 19140/yellow 56 lake',
 'ci 26100',
 'ci 28440',
 'ci 40800',
 'ci 42 090',
 'ci 42051',
 'ci 42053',
 'ci 42053 (green 3)',
 'ci 42090',
 'ci 42090 (blue 1)',
 'ci 42090 (fd&c blue 1)',
 'ci 42090 (fd&c blue no. 1)',
 'ci 42090 / blue 1 lake',
 'ci 42090 / blue 1 lake]',
 'ci 42090 / blue 1]',
 'ci 42090 / blue lake 1]',
 'ci 42090/blue 1',
 'ci 42090/blue 1 lake',
 'ci 42090/blue 1 lake]',
 'ci 42090/blue 1]',
 'ci 42090/blue1',
 'ci 4510/red 28 lake',
 'ci 45100',
 'ci 45350',
 'ci 45380',
 'ci 45380 (red 22)',
 'ci 45380 / red 22 lake',
 'ci 45380 / red 22 lake]',
 'ci 45380/red 22 lake',
 'ci 45410',
 'ci 45410 / red 28 lake',
 'ci 45410/red 28 lake',
 'ci 45410/red 28 lake/ci 77891/titanium dioxide',
 'ci 45410/red 28 lake]',
 'ci 45430',
 'ci 45490 / red 28 lake',
 'ci 45980 / red 22 lake',
 'ci 47000',
 'ci 47005',
 'ci 47005 (yellow 10)',
 'ci 47005 / acid yellow 3',
 'ci 60725',
 'ci 60725 / violet 2',
 'ci 60730',
 'ci 60730 (ext violet 2)',
 'ci 60730 (ext. violet 2)',
 'ci 60730 (fd&c violet n° 2)',
 'ci 60730/ext. violet 2',
 'ci 61565',
 'ci 61565 / green 6',
 'ci 61565/green 6',
 'ci 61570',
 'ci 61570/green 5',
 'ci 73015',
 'ci 73360',
 'ci 73360 (red 30)',
 'ci 73360/red 30 lake',
 'ci 74160',
 'ci 74260',
 'ci 75130 / beta-carotene',
 'ci 75470',
 'ci 75470 / carmine',
 'ci 75470 / carmine]',
 'ci 75470/ carmine',
 'ci 75470/carmine',
 'ci 75470/carmine]',
 'ci 75810',
 'ci 75850 / red 7',
 'ci 77000',
 'ci 77000 / aluminum powder',
 'ci 77000/aluminum powder',
 'ci 77002',
 'ci 77002 / aluminum hydroxide',
 'ci 77002/aluminum hydroxide',
 'ci 77007',
 'ci 77007 (ultramarines)',
 'ci 77007 / ultramarines',
 'ci 77007 / ultramarines]',
 'ci 77007/ultramarines',
 'ci 77007/ultramarines]',
 'ci 77007]',
 'ci 77019',
 'ci 7707 (ultramarines)',
 'ci 77120 / barium sulfate',
 'ci 77120/barium sulfate',
 'ci 77163',
 'ci 77163 / bismuth oxychloride',
 'ci 77163 / bismuth oxychloride]',
 'ci 77163/ bismuth oxychloride',
 'ci 77163/bismuth oxychloride]',
 'ci 77266',
 'ci 77266 / black 2',
 'ci 77266 [nano] / black 2',
 'ci 77266 [nano]/black 2',
 'ci 77268:1',
 'ci 77288',
 'ci 77288 / chromium oxide greens',
 'ci 77288/chromium oxide greens',
 'ci 77288/chromium oxide greens]',
 'ci 77289 / chromium hydroxide green',
 'ci 77289/chromium hydroxide green',
 'ci 77400 / bronze powder',
 'ci 77400 / copper powder',
 'ci 77400/bronze powder',
 'ci 77400/copper powder',
 'ci 77454',
 'ci 77489',
 'ci 77490/yellow 5 lake',
 'ci 77491',
 'ci 77491 (iron oxides)',
 'ci 77491 / iron oxides',
 'ci 77491/2',
 'ci 77491/iron oxides',
 'ci 77492',
 'ci 77492 (iron oxides)',
 'ci 77492 / iron oxides',
 'ci 77492/iron oxides',
 'ci 77492]',
 'ci 77499',
 'ci 77499 / iron oxide',
 'ci 77499 / iron oxides]',
 'ci 77499)',
 'ci 77499)]',
 'ci 77499/iron oxides/isododecane',
 'ci 77499/iron oxides]',
 'ci 77499]',
 'ci 77510',
 'ci 77510 / ferric ammonium ferrocyanide',
 'ci 77510 / ferric ferrocyanide]',
 'ci 77510/ferric ammonium ferrocyanide',
 'ci 77510/ferric ammonium ferrocyanide]',
 'ci 77510/ferric ferrocyanide',
 'ci 77510/ferric ferrocyanide]',
 'ci 77540/ferric ammonium ferrocyanide',
 'ci 77713',
 'ci 77713/magnesium carbonate',
 'ci 77742',
 'ci 77742 / manganese violet',
 'ci 77742/manganese violet',
 'ci 77742/manganese violet]',
 'ci 77820 / silver',
 'ci 77820/silver',
 'ci 77861',
 'ci 77891',
 'ci 77891 / titanium dioxide',
 'ci 77891 / titanium dioxide]',
 'ci 77891 / titanum dioxid',
 'ci 77891 / titanum dioxide',
 'ci 77891/titanium dioxide]',
 'ci 77891/titanum dioxide',
 'ci 77941',
 'ci19140',
 'ci42053',
 'ci42090',
 'ci45410',
 'ci60725',
 'ci74160',
 'ci77266',
 'ci77288',
 'ci77491',
 'ci77492',
 'ci77499',
 'ci77742',
 'ci77891',
 "cire d'abeille)",
 'cire d´abeille)',
 'cire microcristalline)',
 'citric acid [+/- may contain ci 77491',
 'citronellyl methylcrotonate',
 'cl 10316',
 'cl 14720',
 'cl 15985',
 'cl 15985 (yellow 6)',
 'cl 16035',
 'cl 17200',
 'cl 17200 (red 33)',
 'cl 19140',
 'cl 19140 (yellow 5)',
 'cl 42 090',
 'cl 42053',
 'cl 42090',
 'cl 60730',
 'cl 60730 (ext. violet 2)',
 'cl 60730/ext. violet 2',
 'cl 61570',
 'cl 73360',
 'cl 74160',
 'cl 74260',
 'cl 77491',
 'cl 77491 (iron oxides)',
 'cl 77492',
 'cl 77492 (iron oxides)',
 'cl 77499',
 'cl 77499 (iron oxides)',
 'cl 77891',
 'cl 77891 / titanium dioxide]',
 'climbazole',
 'colophonium / rosin',
 'colophonium/rosin',
 'colostrum',
 'colour: isododecane',
 'copper pca',
 'coumarin ± ci 77891',
 'cyclohexasiloxane',
 'cyclomethicone',
 'cyclopentasiloxane',
 'cyclopetasiloxane',
 'cyclotrisiloxane',
 'd&c green no. 5 (ci 61570)',
 'd&c green no. 6 (ci 61565)',
 'd&c red no. 17 (ci 26100)',
 'd&c red no. 30 lake (ci 73360)',
 'd&c red no. 33 (ci 17200)',
 'd&c red no.27',
 'd&c red no.33 (ci 17200)',
 'd&c red no.33 (cl 17200)',
 'd&c violet no. 2 (ci 60725)',
 'denatonium benzoate',
 'diatomaceous earth',
 'diazolidinyl urea',
 'diethyl phthalate',
 'dihydrocholeth-30',
 'dihydroxy methylchromone',
 'dimethicone',
 'dimethiconol',
 'dimethiconol behenate',
 'dimethocne',
 'dimethyl oxobenzo dioxasilane',
 'dimethyl silylate',
 'dimethylmethoxy chromanol',
 'diphenylsiloxy phenyl trimethicone',
 'disetardimonium hectorite',
 'disodium acetyl glucosamine phosphate',
 'disodium edta',
 'disoduim edta',
 'disteardimonium hecionite',
 'disteardimonium hectorine',
 'disteardimonium hectorite',
 'disteardimonium hextorite',
 'disteardominium hectorite',
 'distearoimonium hectorite',
 'distearoylethyl hydroxyethylmonium',
 'disteatdimonium hectorite',
 'disterdimonium hectorite',
 'dmdm hydantoin',
 'dmdm hydation',
 'dmdm hydatoin',
 'dodecene',
 'drometrizole trisiloxane',
 'ectoin',
 'edta',
 'ethyl hexyl methoxycinnamate',
 'ethyl trisiloxane',
 'ethyl-',
 'ethylene brassylate',
 'ethylhexyl methoxycinnmae',
 'ethylhexyl triazone',
 'ethylparaben',
 'etocrylene',
 'ext. d&c violet no. 2 (ci 60730)',
 'ext. d&c violet no. 2 (cl 60730)',
 'ext. d&c violet no.2 (ci 60730)',
 'ext. d&c violet no.2 (cl 60730)',
 'ext. violet 2 (ci 60730)',
 'ext.d&c violet no. 2 (ci 60730)',
 'ext.d&c violet no.2 (ci 60730)',
 'ext.d&c violet no.2 (cl 60730)',
 'fd&c  blue no. 1 (cl 42090)',
 'fd&c blue no. 1 (ci 42090)',
 'fd&c blue no. 1 (cl 42090)',
 'fd&c blue no. 1 aluminum lake (ci 42090)',
 'fd&c blue no.1 (ci 42090)',
 'fd&c blue no.4 (cl 14700)',
 'fd&c green no. 3 (ci 42053)',
 'fd&c red no. 4 (ci 14700)',
 'fd&c red no. 4 (ci 147009)',
 'fd&c red no. 4 (cl 14700)',
 'fd&c red no.4 (ci 14700)',
 'fd&c red no.4 (cl 14700)',
 'fd&c yellow no. 5 (ci 19140)',
 'fd&c yellow no. 5 (cl 19140)',
 'fd&c yellow no. 6 (ci 15985)',
 'fd&c yellow no.5 (ci 19140)',
 'fd&c yellow no.5 (cl 19140)',
 'fd&c yellow no.6 (ci 15985)',
 'fisetin',
 'flavour',
 'fragnance (parfum)',
 'fragrance',
 'fragrance (parfum)',
 'fragrance/parfum',
 'glucosylrutin',
 'green 3 (ci 42053)',
 'green 5 (ci 61570)',
 'guaiazulene',
 'guar hydroxypropyltrimonium chloride',
 'hc blue no. 12',
 'hc blue no. 16',
 'hc blue no. 2',
 'hc red no. 13',
 'hc red no. 3',
 'hc red no.3',
 'hc yellow no. 2',
 'hc yellow no.2',
 'hexadecene',
 'hexadimethrine chloride',
 'hnací plyn: směs uhlovodíků (butan',
 'homosalate',
 'huile minérale)',
 'hydratační pleťový gel: aqua',
 'hydrogen dimethicone',
 'hydrogenated tetradecenyl/methylpentadecane',
 'hydrolyzed pearl',
 'hydroxyacetophenone',
 'hydroxyanthraquinone aminopropyl methyl morpholinium methosulfate',
 'hydroxyethyl',
 'hydroxyethyl cellulose',
 'hydroxyethyl-2-nitro-p-toluidine',
 'hydroxyethyl-cellulose',
 'hydroxyethylcellulose',
 'hydroxyethylcelullose',
 'hydroxyethylpiperazine ethane sulfonic acid',
 'hydroxyisohexyl 3- cyclohexene carboxaldehyde',
 'hydroxyisohexyl 3-cyclohexane carboxaldehyde',
 'hydroxymethoxyphenyl decanone',
 'hydroxymethylpentyl cyclohexencarboxal',
 'hydroxypalmitoyl sphinganine',
 'hydroxypropyl',
 'hydroxypropyl bis(n-hydroxyethyl-p-phenylenediamine hcl',
 'hydroxypropyl bis(n-hydroxyethyl-p-phenylenediamine) hcl',
 'hydroxypropyl guar hydroxypropyltrimonium chloride',
 'hydroxypropyl methylcellulose',
 'hyroxypropyl guar hydroxypropyltrimonium chloride',
 'imidazolidinyl urea',
 'imidazolidinyl urea/lodopropynyl alcohol',
 'imidazouodinyl urea',
 'iodopropynyl butylcarbamate',
 'iron oxides (ci 77491',
 'isobutan',
 'isobutane',
 'isobutene',
 'isododecane',
 'isododevane',
 'isoeicosane',
 'isohexadecana',
 'isohexadecane',
 'isomethyl ionone',
 'isononyl isononanoate',
 'isopentane',
 'isopropyl titanium triisostearate [+/- ci 77891',
 'isoquercitin',
 'isoquercitrin',
 'linoleamidopropyl pg-dimodium chloride phosphate',
 'lipstick: isododecaine',
 'lipstick: isododecane',
 'lodopropynyl butylcarbamate',
 'may contain (+/- ): ci 15880',
 'may contain (+/- ): ci 77891',
 'methicone',
 'methlychloroisothiazolinone',
 'methychloroisothiazolinone',
 'methyl glucose sesquistearate',
 'methyl methacrylate',
 'methyl trimethicone',
 'methylcellulose',
 'methylchloroisotgiazolinone',
 'methylchloroisothiazoline',
 'methylchloroisothiazolinone',
 'methylchloroisothiazolinone methylisothiazolinone',
 'methylchloroisotiazolinone',
 'methylchoroisothiazolinone',
 'methylisothiatolinone',
 'methylisothiazolinone',
 'methylparaben',
 'methylparaben hydrogenated jojoba oil',
 'methylpropional',
 'methylsilanol/silicate crosspolymer',
 'microcristallina cera',
 'missing pdr',
 'montan wax',
 'montmorillonite',
 'myrtrimonium bromide',
 'n',
 "n'-bis(2-hydroxyethyl)-2-nitro-p-phenylenediamine",
 'n-bis(2-hydroxyethyl)-p-phenylenediamine suflate',
 'n-bis(2-hydroxyethyl)-p-phenylenediamine sulfate',
 'n-n-bis(2-hydroxyethyl)-p-phenylenediamine sulfate',
 'nacre powder',
 'neohesperidin dihydrochalcone',
 'obsah neinogenních emulgátorů: 0',
 'obsah neionogenních emulgátorů: 0',
 'obsah neionogenním umulgátorů: 0',
 'obsah tukové fáze do: 15 % hm.',
 'obsah tukové fáze: 4 % hm. max.',
 'obsah tukové fáze: 4% hm.',
 'obsah tukové fáze: do 12 % hm.',
 'obsah tukové fáze: do 14 % hm.',
 'obsah tukové fáze: do 15 % hm.',
 'obsah tukové fáze: do 32 % hm.',
 'obsah tukové fáze: do 7 % hm.',
 'obsah tukové fáze: do 9 % hm. min.',
 'obsah výhradně bezalergenní parfemace: 0',
 'obsahuje: aminfluorid (olaflur) (0',
 'obsahuje: olaflur (aminfluorid) a fluorid cínatý',
 'octadecene',
 'octenidine hci',
 'octenidine hcl',
 'octocrylene',
 'octyldodecanol ozokerite',
 'olaflur',
 'oleamico-1',
 'orange 4 (ci 15510)',
 'oryzanol',
 'ozokerite',
 'p-173808',
 'paraffin',
 'paraffin cyclopentasiloxane',
 'paraffinum liqudium',
 'paraffinum liquidium',
 'paraffinum liquidum',
 'paraffinum liquidum (mineral oil',
 'paraffinum liquidum (mineral oil)',
 'paraffinum liquidum / mineral oil',
 'paraffinum liquidum/mineral oil',
 'paraffinum liquidum/mineral oil/huile minerale',
 'parafinum liquidum',
 'parffinum liquidum',
 'parfum',
 'parfum (fragrance)',
 'parfum (fragrance) (perfume)',
 'parfum / fragrance',
 'parfum / fragrance [+/- may contain: mica',
 'parfum /fragrance',
 'parfum/[fragrance]',
 'parfum/fragrance',
 'parfume',
 'parfum\xa0(fragrance) (perfume)',
 'parraffinum liquidum',
 'parrafin',
 'parrafinum liquidum',
 'peg 90m',
 'peg-12',
 'pentaerithrityl tetra-di-t-butyl hydroxyhydrocinnamate',
 'pentaerythrityl hydrogenated rosinate',
 'pentaerythrityl tetra-d-t-butyl hydroxyhydrocinnamate',
 'pentaerythrityl tetra-di-t-butyl hydroxydrocinnamate',
 'pentaerythrityl tetra-di-t-butyl hydrxyhydrocinnamate',
 'pentaerythrityl tetra-di-t-butylhydroxy hydrocinnamate',
 'pentaerytriphtalate',
 'pentane',
 'pentaphenyl trisilokane',
 'pentaphenyl trisiloxane',
 'pentasodium ethylenediamine tetramethylene phosphonate',
 'pentasodium pentetate',
 'penthaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate',
 'peolyquaternium-37',
 'perfluorooctyl triethoxysilane',
 'petrolatum',
 'phenal trimethicone',
 'phenoxyethanol (and) methylparaben (and) ethylparaben (and) butylparaben (and) propylparaben',
 'phenyl dimethicone',
 'phenyl treimethicone',
 'phenyl trimethicone',
 'phenylbenzimidazole sulfonic acid',
 'phenylpropyldimethylsiloxysilicate',
 'phytantriol',
 'piroctone olamine',
 'poliquaternium-11',
 'poloxamer 124',
 'poloxamer 188',
 'poly(linseed oil)',
 'polyaminopropyl biquanide',
 'polyguaternium-10',
 'polyquanternium-7',
 'polyquater- nium-7',
 'polyquaterniuim-39',
 'polyquaternium-10',
 'polyquaternium-11',
 'polyquaternium-16',
 'polyquaternium-22',
 'polyquaternium-30',
 'polyquaternium-37',
 'polyquaternium-37&propylene glycol dicyprylate/dicaprate&ppg-1-trideceth-6',
 'polyquaternium-39',
 'polyquaternium-4',
 'polyquaternium-47',
 'polyquaternium-51',
 'polyquaternium-52',
 'polyquaternium-55',
 'polyquaternium-6',
 'polyquaternium-68',
 'polyquaternium-69',
 'polyquaternium-7',
 'polyquaternium-76',
 'ppg-12',
 'ppg-14 butyl ether',
 'ppg-5-ceteth-20',
 'ppg-70 tocophereth-100',
 'propan)',
 'propane',
 'propyl-) paraben',
 'propyl-)paraben',
 'propylene',
 'propylene glycol (and) water (and) royal jelly extract',
 'propylparaben',
 'pullulan',
 'pumice',
 'pyridoxine hci',
 'quaternium-18',
 'quaternium-22',
 'quaternium-26',
 'quaternium-80',
 'quaternium-87',
 'quaternium-91',
 'red 33 (ci 17200)',
 'red 4 (ci 14700)',
 'rosin',
 'royal jelly',
 'royal jelly extract',
 'rutin',
 'salicyloyl phytosphingosine',
 'sclareolide',
 'sclerotium gum',
 'sericin',
 'silanetriol',
 'silica dimethy silylate',
 'silica dimethyl silylate',
 'silica dimethyl silylate [nano] / silica dimethyl silylate',
 'silica dimethyl silylate [nano] / silica dimethyl silytate',
 'silica dimethyl silylate [nano]/silica dimethyl silylate',
 'silica silylate',
 'silicone quaternium-16',
 'silicone quaternium-18',
 'silicone quaternium-26',
 'simethicone',
 'sodium benzotriazolyl butylphenol sulfonate',
 'sodium edta',
 'sodium methylparaben',
 'sodium pca',
 'solum fullonum',
 'stearalkonium bentonite',
 'stearyl dimethicone',
 'step 1: isododecane',
 'step 2: isododecane',
 'syntetic wax',
 'synthetic beeswax',
 'synthetic fluorpglogopite',
 'synthetic fluorphlocopite',
 'synthetic fluorphlogopite',
 'synthetic fluorphlogotipe',
 'synthetic wax',
 'tea-hydroiodide',
 'tetrachlorohydrex gly',
 'tetramethyl acetyloctahydronaphthalenes',
 'tetrasodim edta',
 'tetrasodium edta',
 'tetrasodium etidronate',
 'titanium dioxide (ci 77891)',
 'top coat: trimethyl',
 'top coat: trimethyl pentaphenyl trisiloxane',
 'toulene-2',
 'triacontanyl pvp',
 'tribehenin',
 'triclosan',
 'triethanolamine hydroxyethylcellulose',
 'triethoxycaprylylsilane',
 'triethoxycaprylylsilicane',
 'trimethyl pentaphenyl trisiloxane',
 'trimethyl siloxysilicate',
 'trimethylpentandiyl dibenzoate',
 'trimethylpentanediyl dibenzoate',
 'trimethylsiloxylicate',
 'trimethylsiloxyphenyl dimethicone',
 'trimethylsiloxysilicate',
 'trimyristin',
 'tris (tetramethylhydroxypiperidinol)',
 'tris (tetramethylhydroxypiperidinol) citrate',
 'tris (tetramethylhyhroxypiperidinol) citrate',
 'tris(tetramethylhydroxypiperidinol)',
 'tris(tetramethylhydroxypiperidinol) citrate',
 'tris(tetramethylhydroxypiperidinol)citrate',
 'tris-bht mesitylene',
 'trisiloxane',
 'trisodium edta',
 'trisodium edza',
 'trisodium hedta',
 'tropolone',
 'ultramarines (ci 77007)]',
 'utrica dioica',
 'výrobek obsahuje kyselinu hyaluronovou ve formě hyaluronátu sodného',
 'yellow 5 (ci 19140)',
 '±: ci 14720']
 